Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2022-08, with the labels that each got.

#951 chore,fix: upgraded Gemfile and Gemfile.lock
  docs/Gemfile
  docs/Gemfile.lock
Labels: scope: documentation, dependencies, ruby, type: internal

#969 chore: add logging library for more consistent logging output
  package.json
  src/lib/logging.ts
  yarn.lock
Labels: type: internal

#953 fix: find tasks in blockquotes and Obsidian callouts
  docs/getting-started/index.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
  src/Cache.ts
  src/Commands/CreateOrEdit.ts
  src/Commands/ToggleDone.ts
  src/Events.ts
  src/LivePreviewExtension.ts
  src/Query/Filter/ExcludeSubItemsField.ts
  src/Task.ts
  src/main.ts
  tests/Query/Filter/ExcludeSubItemsField.test.ts
  tests/Task.test.ts
Labels: scope: parsing markdown - and global filter

#1005 docs: fix notifications, update auto-suggest
  docs/README.md
  docs/advanced/notifications.md
  docs/getting-started/auto-suggest.md
Labels: scope: documentation

#790 feat: Add regular expression support to text filters
  docs/queries/filters.md
  src/Query/Filter/DescriptionField.ts
  src/Query/Filter/HeadingField.ts
  src/Query/Filter/PathField.ts
  src/Query/Filter/TextField.ts
  tests/Query/Filter/DescriptionField.test.ts
  tests/Query/Filter/PathField.test.ts
Labels: scope: filters

#1017 refactor: simplify Cache.indexFile()
  src/Cache.ts
Labels: scope: parsing markdown - and global filter

#1006 refactor: Remove regexes from Commands files to Task where they can be tested
  src/Commands/CreateOrEdit.ts
  src/Commands/ToggleDone.ts
  src/Task.ts
Labels: type: internal, scope: parsing markdown - and global filter

#1015 docs, test: Document and test regular expression searches
  docs/queries/combining-filters.md
  docs/queries/comments.md
  docs/queries/examples.md
  docs/queries/filters.md
  docs/queries/grouping.md
  docs/queries/layout.md
  docs/queries/limit.md
  docs/queries/regular-expressions.md
  docs/queries/sorting.md
  docs/quick-reference/index.md
  resources/sample_vaults/Tasks-Demo/Filters/Regular Expression Searches.md
  tests/Query/Filter/PathField.test.ts
Labels: scope: documentation

#1053 docs: Fix a couple of typos in regex docs
  docs/queries/regular-expressions.md
Labels: scope: documentation

#1064 docs: Add page on dataview settings for compatibility with Tasks
  docs/other-plugins/dataview.md
  docs/other-plugins/index.md
Labels: scope: documentation

#1074 chore: lefthook was renamed
  package.json
  yarn.lock
Labels: dependencies, javascript, status: ready to merge
