Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2022-06, with the labels that each got.

#744 docs: Add a Quick Reference page to the docs
  docs/_config.yml
  docs/_sass/color_schemes/wider-content.scss
  docs/advanced/index.md
  docs/quick-reference/index.md
Labels: documentation

#579 feat: Add date abbreviations to 'Create or edit Task' modal
  src/Abbrev.ts
  src/ui/EditTask.svelte
Labels: type: enhancement, scope: user interface

#756 chore: Add dependabot.yml to automate updates
  .github/dependabot.yml
Labels: type: internal

#828 docs: Overhaul the Filters documentation
  docs/queries/filters.md
Labels: scope: documentation
