Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2022-10, with the labels that each got.

#1197 Ensure monthly and yearly recurrences
  docs/getting-started/recurring-tasks.md
  resources/sample_vaults/Tasks-Demo/.obsidian/core-plugins.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/styles.css
  resources/sample_vaults/Tasks-Demo/Manual Testing/Recurrence handling invalid dates.md
  src/Recurrence.ts
  tests/Recurrence.test.ts
  tests/Task.test.ts
Labels: type: bug, scope: recurrence

#1229 feat: Faster controls to replace the priority selector
  src/ui/EditTask.svelte
  styles.css
Labels: scope: user interface

#1261 Docs new priority control
  docs/getting-started/priority.md
  resources/screenshots/modal.png
Labels: scope: documentation

#1262 chore: add 'Linking to other pages in the docs' section
  CONTRIBUTING.md
Labels: type: internal
