Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2022-07, with the labels that each got.

#822 feat: Intelligent dynamic auto-complete for entering tasks
  src/Query/DateParser.ts
  src/Suggestor/EditorSuggestorPopup.ts
  src/Suggestor/Suggestor.ts
  src/Task.ts
  src/config/Settings.ts
  src/config/SettingsTab.ts
  src/main.ts
  src/ui/EditTask.svelte
  tests/EditorSuggest.test.ts
Labels: type: enhancement, scope: user interface

#854 chore: deps: bump moment and partially bump obsidian api
  package.json
  yarn.lock
Labels: dependencies

#864 test: Add BooleanField.test.ts with lower-level tests of BooleanField
  src/Query/Filter/BooleanField.ts
  tests/Query/Filter/BooleanField.test.ts
Labels: scope: query logic

#868 fix: Boolean searches with spaces around sub-queries now work
  src/Query/Filter/BooleanField.ts
  tests/Query/Filter/BooleanField.test.ts
Labels: scope: query logic

#867 chore: internal: Fix imports only used for types
  src/Cache.ts
  src/File.ts
  src/LivePreviewExtension.ts
  src/Query/Filter/BooleanField.ts
  src/Query/Filter/FilterInstruction.ts
  src/Query/Filter/FilterInstructions.ts
  src/QueryRenderer.ts
  src/Suggestor/EditorSuggestorPopup.ts
  tests/EditorSuggest.test.ts
  tests/Query.test.ts
Labels: type: internal

#872 chore: deps-dev upgrades, see full list in Description
  package.json
  src/ui/EditTask.svelte
  yarn.lock
Labels: dependencies

#897 docs: Document auto-suggest & improve wording of its settings
  .gitignore
  docs/getting-started/auto-suggest.md
  docs/getting-started/create-or-edit-task.md
  docs/getting-started/dates.md
  resources/screenshots/auto-suggest-edit-incorrect-task.png
  resources/screenshots/auto-suggest-menu-after-due-date.png
  resources/screenshots/auto-suggest-menu-after-due-emoji.png
  resources/screenshots/auto-suggest-menu-after-priority.png
  resources/screenshots/auto-suggest-menu-after-repeat-emoji.png
  resources/screenshots/auto-suggest-menu-after-repeat-text.png
  resources/screenshots/auto-suggest-menu-initial-menu.png
  resources/screenshots/auto-suggest-preview-incorrect-task.png
  resources/screenshots/settings-auto-suggest-task-content.png
  src/config/SettingsTab.ts
  tests/EditorSuggest.test.ts
Labels: scope: documentation, status: next release

#894 perf: Stop many non-task edits triggering a redraw of all active tasks blocks
  src/Cache.ts
  src/QueryRenderer.ts
  src/Recurrence.ts
  src/Sort.ts
  src/Task.ts
  tests/Recurrence.test.ts
  tests/Task.test.ts
  tests/TestingTools/RecurrenceBuilder.test.ts
  tests/TestingTools/RecurrenceBuilder.ts
Labels: status: next release, scope: performance issues

#900 fix: Allow multiple spaces after date emojis, when reading task lines
  docs/getting-started/auto-suggest.md
  src/Task.ts
  tests/Task.test.ts
Labels: status: next release, scope: parsing markdown - and global filter

#902 docs: Fixes to Combining Filters docs (code review)
  docs/queries/combining-filters.md
  docs/queries/filters.md
  docs/quick-reference/index.md
  resources/sample_vaults/Tasks-Demo/Filters/Boolean Combinations.md
Labels: scope: documentation

#893 Add support for grouping by tags
  docs/queries/grouping.md
  src/Query.ts
  src/Query/Group.ts
  src/Query/GroupingTreeNode.ts
  src/Query/IntermediateTaskGroups.ts
  src/Query/TaskGroups.ts
  tests/Group.test.ts
  tests/GroupingTreeNode.test.ts
  tests/Query.test.ts
Labels: scope: grouping

#915 docs: Add 'group by tags' to Quick Ref docs
  docs/queries/grouping.md
  docs/quick-reference/index.md
Labels: scope: documentation

#923 feat: Add 'group by happens'
  docs/queries/grouping.md
  docs/quick-reference/index.md
  src/Query.ts
  src/Query/Filter/HappensDateField.ts
  src/Query/Group.ts
  tests/Group.test.ts
  tests/Query.test.ts
  tests/Query/Filter/HappensDateField.test.ts
Labels: scope: grouping

#939 fix(README, docs): broken links, markdownlint errors
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  README.md
Labels: status: ready to merge

#869 fix: Stop 'Add & edit Task' breaking sub-tags of global filter
  src/Task.ts
  src/ui/EditTask.svelte
  tests/Task.test.ts
Labels: type: bug, scope: user interface, scope: parsing markdown - and global filter
