Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-10, with the labels that each got.

#2312 feat: Add custom grouping by 'date category' and 'time from now'
  docs/Introduction.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Scripting/Custom Grouping.md
  docs/Scripting/Task Properties.md
  src/Scripting/TasksDate.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/TaskProperties.test.task_date_fields.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Scripting/TasksDate.test.ts
Labels: scope: grouping, scope: scripting

#2316 fix: Edit Task modal warns if no date set for recurrence
  src/ui/EditTask.svelte
Labels: scope: edit task

#2325 docs: Add new page 'Known Limitations'
  contributing/.obsidian/snippets/publish-simulation.css
  contributing/publish.css
  docs/.obsidian/snippets/publish-simulation.css
  docs/Getting Started/Create or edit Task.md
  docs/Getting Started/Getting Started.md
  docs/Getting Started/Tags.md
  docs/Getting Started/Use Filename as Default Date.md
  docs/Introduction.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  docs/Support and Help/About Support and Help.md
  docs/Support and Help/Known Limitations.md
  docs/_meta/templates/we are tracking this in discussion.md
  docs/publish.css
Labels: scope: documentation

#2331 feature: Prevent misleading date searches with template text
  docs/Advanced/Daily Agenda.md
  package.json
  resources/sample_vaults/Tasks-Demo/.obsidian/community-plugins.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/templater-obsidian/data.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/templater-obsidian/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/templater-obsidian/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/templater-obsidian/styles.css
  resources/sample_vaults/Tasks-Demo/_meta/templates/daily note template - Templater plugin.md
  src/Query/Filter/DateField.ts
  src/lib/TemplatingPluginTools.ts
  tests/Query/Filter/DateField.test.ts
  tests/TestingTools/ApprovalTestHelpers.ts
  tests/lib/TemplatingPluginTools.test.TemplatingPluginTools_date_templating_error_sample_for_docs.approved.text
  tests/lib/TemplatingPluginTools.test.ts
Labels: scope: filters

#2330 feat: Long query lines can now be split with backslashes
  docs/Queries/About Queries.md
  docs/Queries/Combining Filters.md
  docs/Queries/Comments.md
  docs/Queries/Line Continuations.md
  src/Query/Query.ts
  src/Query/Scanner.ts
  tests/Query.test.ts
  tests/Scanner.test.ts
Labels: scope: parsing markdown, scope: scripting

#2337 refactor: Divide up regex in line continuation code
  src/Query/Scanner.ts
Labels: type: internal, scope: filters

#2338 docs: Wrap long lines in custom filter and group samples
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.heading_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.heading_results.approved.txt
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.symbol_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.symbol_results.approved.txt
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
Labels: scope: documentation, scope: filters, scope: grouping, scope: scripting

#2339 docs: Add new help page 'Breaking Changes'
  docs/Introduction.md
  docs/Support and Help/About Support and Help.md
  docs/Support and Help/Breaking Changes.md
Labels: scope: documentation

#2346 docs: Advertise line continuation characters in docs
  docs/Queries/Explaining Queries.md
  docs/Scripting/Expressions.md
  tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.query.text
  tests/Query/Explain/DocsSamplesForExplain.test.ts
  tests/Scripting/Expression.test.Expression_returns_and_functions.approved.md
  tests/Scripting/Expression.test.ts
Labels: scope: documentation, scope: filters

#2347 docs: Finish Line Continuation and Inline Comments docs
  docs/Introduction.md
  docs/Queries/Combining Filters.md
  docs/Queries/Comments.md
  docs/Queries/Explaining Queries.md
  docs/Queries/Line Continuations.md
  docs/Scripting/Placeholders.md
  docs/Support and Help/Breaking Changes.md
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.query.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.query.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.query.text
  tests/Query/Explain/DocsSamplesForExplain.test.ts
Labels: scope: documentation

#2348 docs: Colour the code in custom filter & group samples
  contributing/Building/Developing with WebStorm.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Scripting/Custom Filters.md
  docs/Scripting/Custom Grouping.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.created_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.done_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.due.advanced_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.due_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.happens_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.scheduled_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.start_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.filename_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.folder_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.path_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.root_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.heading_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.description_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.isDone_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.isRecurring_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.priorityName_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.priorityNumber_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.recurrenceRule_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.tags.advanced_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.tags_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.other_properties_task.urgency_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.name_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.nextSymbol_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.symbol_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.type_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.created_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.done_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.happens_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.scheduled_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.start_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.filename_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.folder_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.path_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.root_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.heading_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.blockLink_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.descriptionWithoutTags_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.description_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.isDone_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.isRecurring_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.originalMarkdown_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.priorityName_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.priorityNumber_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.recurrenceRule_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.tags.advanced_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.tags_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.urgency_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.special_cases_formatting_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.statuses_task.status.name_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.statuses_task.status.nextSymbol_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.statuses_task.status.symbol_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.statuses_task.status.type_docs.approved.md
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
Labels: scope: documentation, scope: scripting

#2350 docs: Add Recurring Tasks's 'Known Issues' to 'Known Limitations
  docs/Getting Started/Recurring Tasks.md
Labels: scope: documentation

#2351 docs: Mermaid status diagrams now machine-generated
  docs/Getting Started/Statuses/Example Statuses.md
  src/StatusRegistry.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_core-statuses.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_custom-statuses.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_important-cycle.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_toggle-does-nothing.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_AnuPpuccin_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Aura_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Ebullientworks_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_ITS_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_LYT_Mode_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Minimal_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Things_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/StatusRegistry.test.ts
Labels: scope: documentation, type: internal

#2352 docs: Add page 'Recurring Tasks and Custom Statuses'
  docs/Getting Started/Recurring Tasks.md
  docs/Getting Started/Statuses.md
  docs/Getting Started/Statuses/About Statuses.md
  docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md
  docs/Getting Started/Statuses/Status Types.md
  docs/Introduction.md
  src/StatusRegistry.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled-with-unconventional-symbols.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/StatusRegistry.test.ts
Labels: scope: documentation, scope: task states, scope: recurrence

#2359 docs: Major enhancements to 'Recurring Tasks' docs
  docs/Getting Started/Recurring Tasks.md
  docs/images/modal-showing-date-needed-on-recurring-task.png
Labels: scope: documentation, scope: recurrence

#2360 docs,fix: Refine the wording of the warning in Edit Task modal
  docs/Getting Started/Create or edit Task.md
  docs/images/modal-showing-date-needed-on-recurring-task.png
  src/ui/EditTask.svelte
Labels: scope: documentation, scope: edit task

#2369 docs: Fix typo in grouping.md (filenameWithoutExtension)
  docs/Queries/Grouping.md
Labels: scope: documentation

#2373 refactor: Introduce (empty) SearchInfo class
  src/Query/Filter/BooleanField.ts
  src/Query/Filter/Filter.ts
  src/Query/SearchInfo.ts
  tests/CustomMatchers/CustomMatchersForFilters.test.ts
  tests/CustomMatchers/CustomMatchersForFilters.ts
  tests/CustomMatchers/jest.custom_matchers.setup.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/Query.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
  tests/TestingTools/FilterTestHelpers.ts
Labels: type: internal

#2374 recfactor: SearchInfo now contains list of tasks being searched
  src/Query/Query.ts
  src/Query/SearchInfo.ts
  tests/CustomMatchers/CustomMatchersForFilters.test.ts
  tests/CustomMatchers/CustomMatchersForFilters.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/Query.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Query/SearchInfo.test.ts
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
  tests/TestingTools/FilterTestHelpers.ts
Labels: type: internal

#2376 refactor: Add SearchInfo param to GrouperFunction
  src/Query/Grouper.ts
  src/Query/Query.ts
  src/Query/QueryResult.ts
  src/Query/SearchInfo.ts
  src/Query/TaskGroupingTree.ts
  src/Query/TaskGroups.ts
  tests/CustomMatchers/CustomMatchersForFilters.test.ts
  tests/CustomMatchers/CustomMatchersForFilters.ts
  tests/CustomMatchers/CustomMatchersForGrouping.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/Query.test.ts
  tests/Query/Filter/BacklinkField.test.ts
  tests/Query/Filter/CreatedDateField.test.ts
  tests/Query/Filter/DoneDateField.test.ts
  tests/Query/Filter/DueDateField.test.ts
  tests/Query/Filter/FilenameField.test.ts
  tests/Query/Filter/FolderField.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Query/Filter/HappensDateField.test.ts
  tests/Query/Filter/HeadingField.test.ts
  tests/Query/Filter/PathField.test.ts
  tests/Query/Filter/PriorityField.test.ts
  tests/Query/Filter/RecurrenceField.test.ts
  tests/Query/Filter/RecurringField.test.ts
  tests/Query/Filter/RootField.test.ts
  tests/Query/Filter/ScheduledDateField.test.ts
  tests/Query/Filter/StartDateField.test.ts
  tests/Query/Filter/StatusField.test.ts
  tests/Query/Filter/StatusNameField.test.ts
  tests/Query/Filter/StatusTypeField.test.ts
  tests/Query/Filter/TagsField.test.ts
  tests/Query/Filter/UrgencyField.test.ts
  tests/Query/QueryResult.test.ts
  tests/Query/SearchInfo.test.ts
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
  tests/TaskGroups.test.ts
  tests/TestingTools/FilterTestHelpers.ts
Labels: type: internal

#2377 feat: Custom grouping accesses Query Properties directly, without Placeholders
  docs/Introduction.md
  docs/Queries/Grouping.md
  docs/Quick Reference.md
  docs/Scripting/Custom Grouping.md
  docs/Scripting/Query Properties.md
  src/Query/Filter/FunctionField.ts
  src/Query/SearchInfo.ts
  src/Scripting/QueryContext.ts
  src/Scripting/TaskExpression.ts
  tests/CustomMatchers/CustomMatchersForGrouping.ts
  tests/Query.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Query/SearchInfo.test.ts
  tests/Scripting/Expression.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.path_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.path_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
  tests/Scripting/TaskExpression.test.ts
  tests/Scripting/TaskProperties.test.ts
  tests/TaskGroups.test.ts
Labels: scope: grouping, scope: scripting

#2378 feat: Custom filters access Query Properties directly, without Placeholders
  docs/Introduction.md
  docs/Queries/Filters.md
  docs/Scripting/Custom Filters.md
  src/Query/Filter/FunctionField.ts
  src/Scripting/TaskExpression.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.folder_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.folder_results.approved.txt
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
  tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
Labels: scope: filters, scope: scripting

#2382 fix: Correct (unreleased) display of special chars in Mermaid status diagrams
  docs/Getting Started/Statuses/Example Statuses.md
  src/StatusRegistry.ts
  src/lib/HTMLCharacterEntities.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_core-statuses.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_custom-statuses.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_important-cycle.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_toggle-does-nothing.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_AnuPpuccin_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Aura_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Ebullientworks_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_ITS_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_LYT_Mode_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Minimal_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Things_Table.approved.mermaid.md
  tests/StatusRegistry.test.ts
  tests/lib/HTMLCharacterEntities.test.ts
Labels: scope: task states

#2383 feat: Enable visualisation of the Status settings
  resources/sample_vaults/Tasks-Demo/.gitignore
  src/Config/SettingsTab.ts
  src/StatusRegistryReport.ts
  tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
  tests/StatusRegistryReport.test.ts
Labels: scope: task states

#2384 fix: 'Add All Unknown Status Types' now sorts new statuses by symbol
  docs/Getting Started/Statuses/Status Settings.md
  docs/images/settings-custom-statuses-add-unknown-statuses.png
  src/StatusRegistry.ts
  tests/StatusRegistry.test.ts
Labels: scope: task states

#2385 feat: Statuses report now shows a Status Settings table
  src/Config/StatusSettings.ts
  src/StatusRegistryReport.ts
  tests/Config/StatusSettings.test.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
  tests/StatusRegistryReport.test.StatusRegistryReport_should_tabulate_StatusSettings.approved.md
  tests/StatusRegistryReport.test.ts
Labels: scope: task states
