Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-12, with the labels that each got.

#2465 perf: Do not index attachments after plugin has loaded
  src/Cache.ts
Labels: scope: performance issues

#2466 feat: Add Tasks docs to the HelpMate plugin
  manifest.json
Labels: scope: documentation

#2467 contrib: Update Node version in Contributing guide
  contributing/Building/Setting up build environment.md
Labels: scope: documentation

#2468 vault: Update plugins in Tasks-Demo vault
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/cmdr/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/cmdr/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/cmdr/styles.css
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/dataview/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/dataview/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/dataview/styles.css
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-style-settings/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-style-settings/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/styles.css
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/templater-obsidian/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/templater-obsidian/manifest.json
Labels: scope: sample vault

#2469 vault: Install the HelpMate plugin, to access Tasks help
  resources/sample_vaults/Tasks-Demo/.obsidian/community-plugins.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/data.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/styles.css
Labels: scope: sample vault

#2470 refactor: fix async/await warnings in QueryRenderer.ts
  src/QueryRenderer.ts
Labels: type: internal

#2472 fix: Debug logging in File.ts works; better logging
  src/File.ts
  src/QueryRenderer.ts
  src/Task.ts
  src/lib/LogTasksHelper.ts
Labels: type: internal

#2475 docs: fix typo about comment tasks in getting-started
  docs/Getting Started/Getting Started.md
Labels: scope: documentation

#2477 docs: Fix typo
  docs/Getting Started/Dates.md
Labels: scope: documentation

#2483 refactor: Rename postpone symbols and standardise parameter order
  src/QueryRenderer.ts
Labels: type: internal

#2473 test: test postponed task and date creation
  tests/Scripting/Postponer.test.ts
  tests/Scripting/TasksDate.test.ts
Labels: scope: user interface

#2486 fix: Postponing now works repeatedly
  src/Scripting/TasksDate.ts
  tests/Scripting/TasksDate.test.ts
Labels: scope: user interface

#2476 feat: add "change task status" context menu
  src/Task.ts
  src/TaskLineRenderer.ts
Labels: scope: user interface, scope: task states

#2489 fix: Correctly indent Tasks search results in Live Preview
  styles.css
Labels: scope: css styling

#2490 refactor: rename variables in postpone code
  src/QueryRenderer.ts
  src/Scripting/Postponer.ts
  tests/Scripting/Postponer.test.ts
Labels: type: internal

#2492 docs: Create new 'Editing/' section in the documentation
  docs/Editing/About Editing.md
  docs/Editing/Auto-Suggest.md
  docs/Editing/Create or edit Task.md
  docs/Getting Started/About Getting Started.md
  docs/Introduction.md
Labels: scope: documentation

#2493 feat: Improve usability of Statuses context menu
  src/TaskLineRenderer.ts
  src/ui/Menus/StatusMenu.ts
  tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_full_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_short_mode.approved.html
  tests/__mocks__/obsidian.ts
  tests/ui/Menus/StatusMenu.test.ts
Labels: scope: user interface, scope: task states

#2494 test: improve TaskLineRenderer tests
  tests/TaskLineRenderer.test.ts
Labels: type: internal

#2495 internal: Add Priorities menu (not yet used anywhere in the plugin)
  src/ui/EditInstructions/PriorityInstructions.ts
  src/ui/EditInstructions/TaskEditingInstruction.ts
  src/ui/Menus/PriorityMenu.ts
  src/ui/Menus/StatusMenu.ts
  src/ui/Menus/TaskEditingMenu.ts
  tests/ui/EditInstructions/PriorityInstructions.test.ts
  tests/ui/Menus/PriorityMenu.test.ts
Labels: type: internal

#2497 feature: Experimental changes to (unreleased) Postpone menu options
  src/QueryRenderer.ts
  src/Scripting/Postponer.ts
  tests/Scripting/Postponer.test.ts
Labels: scope: user interface

#2499 fix: better menu items to postpone future dates
  src/Scripting/Postponer.ts
  tests/Scripting/Postponer.test.ts
Labels: type: internal

#2501 fix: prevent postpone from overwriting invalid dates.
  src/Scripting/Postponer.ts
  src/Task.ts
  tests/Scripting/Postponer.test.ts
Labels: scope: user interface

#2508 fix: Bug-fixes and tests for the new Statuses context menu
  src/Status.ts
  src/Task.ts
  src/ui/Menus/StatusMenu.ts
  tests/Status.test.ts
  tests/Task.test.ts
Labels: scope: user interface

#2515 test: improve `testLayoutOptions()` test function to have the expected description in one parameter with other expected components
  tests/TaskLineRenderer.test.ts
Labels: type: internal

#2513 fix: Prevent default action when clicking the postpone button
  src/QueryRenderer.ts
Labels: scope: user interface, display: live preview

#2521 refactor: extract QueryLayoutOptions from LayoutOptions
  src/IQuery.ts
  src/InlineRenderer.ts
  src/Query/Query.ts
  src/QueryLayoutOptions.ts
  src/QueryRenderer.ts
  src/TaskLayout.ts
  src/TaskLineRenderer.ts
  src/TaskSerializer/DataviewTaskSerializer.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  tests/TaskLayout.test.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal

#2518 test: test adding data attributes with only name & only value
  tests/CustomMatchers/CustomMatchersForRendering.ts
  tests/CustomMatchers/jest.custom_matchers.setup.ts
  tests/TaskFieldRenderer.test.ts
Labels: type: internal

#2523 test: use the toHaveDataAttributes() matcher in TaskFieldRenderer tests
  tests/TaskFieldRenderer.test.ts
Labels: type: internal

#2516 fix: Cycle through statuses until TODO is found when marking recurring tasks as DONE
  src/Task.ts
  tests/Commands/ToggleDone.test.ts
Labels: scope: recurrence

#2526 refactor: Move new status calculation for recurring tasks to StatusRegistry
  src/StatusRegistry.ts
  src/Task.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/StatusRegistry.test.ts
  tests/TestingTools/ApprovalTestHelpers.ts
  tests/TestingTools/StatusExamples.ts
  tests/TestingTools/StatusesTestHelpers.ts
  tests/TestingTools/VerifyStatuses.ts
Labels: type: internal, scope: recurrence

#2527 fix: Next recurrent of recurring tasks is now always TODO, IN_PROGRESS or space
  src/StatusRegistry.ts
  tests/StatusRegistry.test.ts
Labels: scope: recurrence

#2528 feat: Show non-standard recurrence transitions in Mermaid diagrams
  src/StatusRegistry.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled-with-unconventional-symbols.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled.approved.detailed.mermaid.md
Labels: scope: recurrence

#2530 feat: Update "Check your Statuses" text for new behaviour
  src/StatusSettingsReport.ts
  tests/StatusSettingsReport.test.StatusSettingsReport_should_include_problems_in_table.approved.md
Labels: scope: task states, scope: recurrence

#2534 docs: Updates for recent fixes of statuses with recurrence
  docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md
  docs/images/settings-statuses-report.png
Labels: scope: documentation

#2535 feat: Add 'full mode' instruction, to negate 'short mode'
  docs/Introduction.md
  docs/Queries/Global Query.md
  docs/Queries/Layout.md
  docs/Quick Reference.md
  src/Query/Query.ts
  tests/Query.test.ts
Labels: scope: filters, scope: rendering of tasks

#2536 feat: Make 'explain' show 'group by' commands
  docs/Introduction.md
  docs/Queries/Explaining Queries.md
  docs/Queries/Line Continuations.md
  docs/Queries/Regular Expressions.md
  docs/Scripting/Placeholders.md
  src/Query/Filter/Field.ts
  src/Query/Filter/FunctionField.ts
  src/Query/Filter/MultiTextField.ts
  src/Query/Filter/UrgencyField.ts
  src/Query/Grouper.ts
  src/Query/Query.ts
  tests/Config/DebugSettings.test.ts
  tests/Query.test.ts
  tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
  tests/Query/Filter/DueDateField.test.ts
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_filters-date-examples.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-week-month-quarter-year.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-weekday.approved.explanation.text
  tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
  tests/TaskGroups.test.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: scope: grouping, scope: explain

#2537 fix: Tidy up blank lines in 'explain' output
  docs/Queries/Explaining Queries.md
  src/Query/Explain/Explainer.ts
  tests/Config/DebugSettings.test.ts
  tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
  tests/Query/Explain/Explainer.test.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: scope: explain

#2538 feat: Use indentation to separate global & code block query explanation
  docs/Queries/Explaining Queries.md
  docs/Queries/Line Continuations.md
  docs/Queries/Regular Expressions.md
  docs/Scripting/Placeholders.md
  src/Query/Explain/Explainer.ts
  src/Query/Filter/Filter.ts
  src/lib/QueryRendererHelper.ts
  tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
  tests/Query/Explain/Explainer.test.ts
  tests/Query/Filter/Filter.test.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: scope: explain

#2539 feat: Make 'explain' show 'sort by' commands
  docs/Introduction.md
  docs/Queries/Explaining Queries.md
  docs/Queries/Line Continuations.md
  docs/Queries/Regular Expressions.md
  docs/Scripting/Placeholders.md
  src/Query/Explain/Explainer.ts
  src/Query/Filter/Field.ts
  src/Query/Filter/TagsField.ts
  src/Query/Sorter.ts
  tests/Config/DebugSettings.test.ts
  tests/Query.test.ts
  tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
  tests/Query/Explain/Explainer.test.ts
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_filters-date-examples.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-week-month-quarter-year.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-weekday.approved.explanation.text
  tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
  tests/Sort.test.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: scope: sorting, scope: explain

#2524 test: test `LayoutOptions` with the full task from `TaskBuilder`
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2525 test: improve rendering tests with matchers
  tests/CustomMatchers/CustomMatchersForRendering.ts
  tests/CustomMatchers/jest.custom_matchers.setup.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2550 feat: Add initial support for Cancelled Date field
  docs/Advanced/Styling.md
  docs/Getting Started/Dates.md
  docs/Reference/Task Formats/Dataview Format.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  docs/Scripting/Task Properties.md
  docs/images/settings-optional-date-fields.png
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
  resources/sample_vaults/Tasks-Demo/Formats/Dataview Format.md
  resources/sample_vaults/Tasks-Demo/Formats/Tasks Format.md
  src/Commands/CreateOrEditTaskParser.ts
  src/Config/Settings.ts
  src/Config/SettingsTab.ts
  src/Status.ts
  src/Task.ts
  src/TaskFieldRenderer.ts
  src/TaskLayout.ts
  src/TaskSerializer/DataviewTaskSerializer.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/TaskSerializer/index.ts
  tests/CustomMatchers/CustomMatchersForTaskSerializer.ts
  tests/Query.test.ts
  tests/Scripting/TaskProperties.test.task_other_fields.approved.md
  tests/Task.test.ts
  tests/TaskLayout.test.ts
  tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
  tests/TaskLineRenderer.test.ts
  tests/TaskSerializer/DataviewTaskSerializer.test.ts
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Dates_dataview-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Dates_dataview-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Dates_tasksPluginEmoji-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Dates_tasksPluginEmoji-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.ts
  tests/TaskSerializer/TaskSerializer.test.ts
  tests/TestHelpers.ts
  tests/TestingTools/TaskBuilder.test.ts
  tests/TestingTools/TaskBuilder.ts
  tests/ui/Menus/StatusMenu.test.ts
Labels: scope: task dates and times, scope: parsing markdown

#2553 feat: Add all Tasks query block instructions for Cancelled Dates
  docs/Getting Started/Dates.md
  docs/How To/Find tasks with invalid data.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Queries/Layout.md
  docs/Queries/Sorting.md
  docs/Quick Reference.md
  docs/Scripting/Task Properties.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Invalid Dates.md
  src/Query/Filter/CancelledDateField.ts
  src/Query/FilterParser.ts
  src/Query/Query.ts
  src/Task.ts
  tests/DocumentationSamples/ValidateTasks.test.ts
  tests/DocumentationSamples/ValidateTasks.test.validate-tasks_find-unread-emojis.approved.text
  tests/DocumentationSamples/ValidateTasks.test.validate-tasks_find_problem_dates.approved.text
  tests/Query.test.ts
  tests/Query/Filter/CancelledDateField.test.ts
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.cancelled_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.cancelled_results.approved.txt
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.cancelled_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.cancelled_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/TaskProperties.test.task_dates.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/TestHelpers.ts
Labels: scope: filters, scope: task dates and times
