Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-11, with the labels that each got.

#2393 feat: Enable logging configuration
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
  src/Config/Settings.ts
  src/Query/Query.ts
  src/lib/logging.ts
  src/main.ts
Labels: type: internal

#2397 feat: Add optional debug logging of searches and file handling
  src/Cache.ts
  src/Config/Settings.ts
  src/File.ts
  src/IQuery.ts
  src/Query/Query.ts
  src/QueryRenderer.ts
  src/Task.ts
  src/TasksEvents.ts
  tests/Config/Settings.test.ts
Labels: type: internal, scope: performance issues

#2362 fix: Allow indenting tasks while suggest popup present
  src/Suggestor/EditorSuggestorPopup.ts
Labels: scope: auto-suggest

#2399 feat: "Review and check your Statuses" now shows any problems
  docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md
  src/StatusRegistryReport.ts
  src/StatusSettingsReport.ts
  tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
  tests/StatusSettingsReport.test.StatusSettingsReport_should_include_problems_in_table.approved.md
  tests/StatusSettingsReport.test.StatusSettingsReport_should_tabulate_StatusSettings.approved.md
  tests/StatusSettingsReport.test.ts
Labels: scope: task states

#2400 feat: Colour-code the Mermaid status diagrams for readability
  docs/Getting Started/Statuses/Example Statuses.md
  docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md
  src/StatusRegistry.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_core-statuses.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_custom-statuses.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled-with-unconventional-symbols.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_important-cycle.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.detailed.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_toggle-does-nothing.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_AnuPpuccin_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Aura_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Ebullientworks_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_ITS_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_LYT_Mode_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Minimal_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Things_Table.approved.mermaid.md
  tests/StatusRegistry.test.ts
  tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
Labels: scope: task states

#2406 docs: Document 'Review and check your Statuses' report
  docs-snippets/snippet-statuses-overview.md
  docs/Getting Started/Statuses.md
  docs/Getting Started/Statuses/About Statuses.md
  docs/Getting Started/Statuses/Check your Statuses.md
  docs/Getting Started/Statuses/Core Statuses.md
  docs/Getting Started/Statuses/Custom Statuses.md
  docs/Getting Started/Statuses/Editing a Status.md
  docs/Getting Started/Statuses/Example Statuses.md
  docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md
  docs/Getting Started/Statuses/Status Settings.md
  docs/Getting Started/Statuses/Status Types.md
  docs/How To/Set up custom statuses.md
  docs/How To/Style custom statuses.md
  docs/Introduction.md
  docs/Reference/Status Collections/About Status Collections.md
  docs/images/settings-core-statuses.png
  docs/images/settings-statuses-initial.png
  docs/images/settings-statuses-report.png
Labels: scope: documentation, scope: task states

#2407 test: include description and tags in Visualise HTML tests
  tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_full_mode.approved.html
  tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_short_mode.approved.html
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2403 refactor: extract data and behaviour of layout parameters
  src/TaskLineRenderer.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2412 `docs` - changed wrong definition of done
  docs/Getting Started/Statuses.md
Labels: scope: documentation, scope: task states

#2413 vault: Add Templates to create tasks with range of dates, for testing.
  resources/sample_vaults/Tasks-Demo/_meta/templates/tasks with range of all dates - Templater plugin.md
  resources/sample_vaults/Tasks-Demo/_meta/templates/tasks with range of due dates - Templater plugin.md
  resources/sample_vaults/Tasks-Demo/_meta/templates/tasks with range of scheduled dates - Templater plugin.md
  resources/sample_vaults/Tasks-Demo/_meta/templates/tasks with range of start dates - Templater plugin.md
Labels: scope: sample vault

#2421 build(deps-dev): bump svelte, svelte-check and svelte-preprocess
  yarn.lock
Labels: dependencies, javascript

#2422 build(deps-dev): Various eslint dependencies
  yarn.lock
Labels: dependencies, javascript

#2423 build(deps): bump typescript and tslib
  yarn.lock
Labels: dependencies, javascript

#2424 build(deps): bump jest dependencies
  yarn.lock
Labels: dependencies, javascript

#2408 refactor: move to FieldLayoutDetail and linline 2 functions
  src/TaskLineRenderer.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2425 refactor: add a container for `FieldLayoutDetails` and get data attributes from it
  src/TaskLineRenderer.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2436 refactor: create TaskFieldRenderer.ts
  src/TaskFieldRenderer.ts
  src/TaskLineRenderer.ts
  tests/TaskFieldRenderer.test.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2437 chore: Add comments to find locations for common edits
  contributing/Code/How do I add a new field to the Task class.md
  contributing/Code/How do I add a new task filter.md
  docs/Advanced/Styling.md
  docs/Getting Started/Dates.md
  docs/How To/Find tasks with invalid data.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Queries/Layout.md
  docs/Queries/Sorting.md
  docs/Quick Reference.md
  docs/Reference/Task Formats/Dataview Format.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  docs/Scripting/Task Properties.md
  src/Commands/CreateOrEditTaskParser.ts
  src/Query/FilterParser.ts
  src/Suggestor/Suggestor.ts
  src/Task.ts
  src/TaskFieldRenderer.ts
  src/TaskLayout.ts
  src/TaskLineRenderer.ts
  src/TaskSerializer/DataviewTaskSerializer.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/TaskSerializer/index.ts
  src/ui/EditTask.svelte
  tests/Commands/CreateOrEditTaskParser.test.ts
  tests/CustomMatchers/CustomMatchersForTaskSerializer.ts
  tests/Query.test.ts
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/TaskProperties.test.ts
  tests/Suggestor/Suggestor.test.ts
  tests/Task.test.ts
  tests/TaskSerializer/DataviewTaskSerializer.test.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
  tests/TaskSerializer/TaskSerializer.test.ts
  tests/TestingTools/TaskBuilder.ts
Labels: type: internal

#2439 refactor: improve rendering code quality
  src/InlineRenderer.ts
  src/QueryRenderer.ts
  src/TaskFieldRenderer.ts
  src/TaskLineRenderer.ts
  tests/TaskFieldRenderer.test.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2442 refactor: add data attributes in `TaskFieldRenderer` instead of returning them
  src/TaskFieldRenderer.ts
  src/TaskLineRenderer.ts
  tests/TaskFieldRenderer.test.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#2446 fix: Prevent default click behavior when jumping to a task
  src/QueryRenderer.ts
Labels: scope: backlinks

#2447 docs: add example for query options and using callouts
  docs/Queries/About Queries.md
Labels: scope: documentation

#2418 feat: Add support for case-insensitive queries
  docs/Queries/About Queries.md
  src/Query/Filter/DateField.ts
  src/Query/Filter/Field.ts
  src/Query/Filter/FilterInstructionsBasedField.ts
  src/Query/Filter/FunctionField.ts
  src/Query/Filter/MultiTextField.ts
  src/Query/Filter/PriorityField.ts
  src/Query/Filter/StatusTypeField.ts
  src/Query/Filter/TagsField.ts
  src/Query/Filter/TextField.ts
  src/Query/FilterParser.ts
  src/Query/Query.ts
  tests/Query.test.ts
Labels: scope: filters

#2450 refactor,docs: Refactor code & document case-insensitive queries
  docs/Introduction.md
  docs/Queries/About Queries.md
  docs/Queries/Examples.md
  docs/_meta/templates/insert line in to What's New.md
  src/Query/Filter/DateField.ts
  src/Query/Filter/FilterInstruction.ts
  src/Query/Filter/FilterInstructionsBasedField.ts
  src/Query/Filter/TagsField.ts
  tests/Query/Filter/DateField.test.ts
  tests/Query/Filter/ExcludeSubItemsField.test.ts
  tests/Query/Filter/FilterInstruction.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Query/Filter/PriorityField.test.ts
  tests/Query/Filter/RecurringField.test.ts
  tests/Query/Filter/StatusField.test.ts
  tests/Query/Filter/TagsField.test.ts
  tests/Query/Filter/TextField.test.ts
Labels: scope: filters

#2191 feat: Add a button, with context menu, to "postpone" tasks
  src/Query/Query.ts
  src/QueryRenderer.ts
  src/Scripting/TasksDate.ts
  src/TaskLayout.ts
  styles.css
  tests/TaskLayout.test.ts
Labels: scope: task dates and times

#2453 refactor: Extract functions from postpone code, and start testing
  src/QueryRenderer.ts
  src/lib/QueryRendererHelper.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: type: internal

#2454 feat: Enable postponing of start dates
  src/QueryRenderer.ts
  src/lib/QueryRendererHelper.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: type: enhancement, scope: task dates and times

#2455 feat: postponement usability improvements
  src/QueryRenderer.ts
  src/Scripting/Postponer.ts
  src/lib/QueryRendererHelper.ts
  tests/Scripting/Postponer.test.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: scope: user interface, scope: task dates and times
