Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-05, with the labels that each got.

#1928 refactor, test: Re-enable 'show all suggested text' test
  src/Config/Settings.ts
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.ts
  tests/TestingTools/VerifyMarkdownTable.ts
Labels: type: internal, scope: auto-suggest

#1941 feat: Add 'sort by recurring' instruction
  docs/Queries/Sorting.md
  docs/Quick Reference.md
  src/Query/Filter/RecurringField.ts
  tests/Query.test.ts
  tests/Query/Filter/RecurringField.test.ts
  tests/TestingTools/TaskBuilder.ts
Labels: scope: sorting

#1944 feat: Add 'group by urgency'
  docs/Introduction.md
  docs/Queries/Grouping.md
  docs/Quick Reference.md
  src/Query/Filter/UrgencyField.ts
  tests/Query.test.ts
  tests/Query/Filter/UrgencyField.test.ts
Labels: scope: grouping, scope: urgency

#1921 refactor: addgroupheading() refactoring
  src/QueryRenderer.ts
Labels: type: internal, scope: grouping

#1946 vault: Update Tasks plugin in demo vault to 3.6.0
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/manifest.json
Labels: scope: sample vault

#1949 refactor: Simplify BacklinkField & add test for #1927
  src/Query/Filter/BacklinkField.ts
  tests/Query/Filter/BacklinkField.test.ts
  tests/Task.test.ts
  tests/TestHelpers.ts
Labels: scope: grouping

#1954 feat: reverse sorting of groups
  src/Query/Filter/Field.ts
  src/Query/Filter/MultiTextField.ts
  src/Query/FilterParser.ts
  src/Query/Grouper.ts
  src/Query/TaskGroups.ts
  tests/CustomMatchers/CustomMatchersForGrouping.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
  tests/Query.test.ts
  tests/Query/Filter/BacklinkField.test.ts
  tests/Query/Filter/CreatedDateField.test.ts
  tests/Query/Filter/DoneDateField.test.ts
  tests/Query/Filter/DueDateField.test.ts
  tests/Query/Filter/FilenameField.test.ts
  tests/Query/Filter/FolderField.test.ts
  tests/Query/Filter/HappensDateField.test.ts
  tests/Query/Filter/HeadingField.test.ts
  tests/Query/Filter/PathField.test.ts
  tests/Query/Filter/PriorityField.test.ts
  tests/Query/Filter/RecurrenceField.test.ts
  tests/Query/Filter/RecurringField.test.ts
  tests/Query/Filter/RootField.test.ts
  tests/Query/Filter/ScheduledDateField.test.ts
  tests/Query/Filter/StartDateField.test.ts
  tests/Query/Filter/StatusField.test.ts
  tests/Query/Filter/StatusNameField.test.ts
  tests/Query/Filter/StatusTypeField.test.ts
  tests/Query/Filter/TagsField.test.ts
  tests/Query/Filter/UrgencyField.test.ts
  tests/TaskGroups.test.ts
Labels: scope: grouping

#1958 feat: Optionally put next recurrence below current task
  docs/Getting Started/Recurring Tasks.md
  docs/Getting Started/Settings.md
  docs/images/settings-recurrence-location.png
  src/Commands/ToggleDone.ts
  src/Config/Settings.ts
  src/Config/SettingsTab.ts
  src/LivePreviewExtension.ts
  src/Task.ts
  src/TaskLineRenderer.ts
  tests/Task.test.ts
Labels: scope: recurrence

#1957 refactor: move TaskGroupingTreeStorage to TaskGroups
  src/Query/GroupDisplayHeadingSelector.ts
  src/Query/TaskGroupingTree.ts
  src/Query/TaskGroupingTreeStorage.ts
  src/Query/TaskGroups.ts
  tests/GroupingTreeNode.test.ts
Labels: type: internal, scope: grouping

#1963 feat: Add 'limit groups to <number> tasks'
  docs/Queries/Limiting.md
  src/Query/Query.ts
  src/Query/TaskGroup.ts
  src/Query/TaskGroups.ts
  tests/Query.test.ts
  tests/TaskGroups.test.ts
Labels: scope: grouping, status: user docs need work

#1973 docs: More group limits docs (+minor test & refactor)
  docs/Getting Started/Recurring Tasks.md
  docs/Getting Started/Settings.md
  docs/Introduction.md
  docs/Queries/Grouping.md
  docs/Queries/Limiting.md
  docs/Quick Reference.md
  src/Query/Query.ts
  tests/Query.test.ts
Labels: scope: grouping

#1975 jsdoc,comment: Copy 2 tiny additions from my fork
  src/Query/Filter/Field.ts
  src/Query/Grouper.ts
Labels: type: internal

#1976 refactor: Simplify grouping code in Field.ts
  src/Query/Filter/Field.ts
  src/Query/FilterParser.ts
Labels: type: internal, scope: grouping

#1977 refactor: Simplify sorting code in Field.ts
  src/Query/Filter/Field.ts
  src/Query/FilterParser.ts
  tests/Query/Filter/Field.test.ts
  tests/Query/Filter/RecurringField.test.ts
  tests/Query/Filter/TagsField.test.ts
Labels: type: internal, scope: sorting

#1979 test: More custom matchers, for easier Task testing
  tests/CustomMatchers/CustomMatchersForTaskBuilder.ts
  tests/CustomMatchers/CustomMatchersForTasks.ts
  tests/CustomMatchers/jest.custom_matchers.setup.ts
  tests/Task.test.ts
Labels: type: internal

#1952 fix: prevent Obsidian 1.3.0 log spam
  src/InlineRenderer.ts
  src/QueryRenderer.ts
  src/TaskLineRenderer.ts
  tests/TaskLineRenderer.test.ts
Labels: scope: rendering of tasks

#1980 test: Add jest custom matcher toEqualMoment()
  tests/CustomMatchers/CustomMatchersForDates.ts
  tests/CustomMatchers/jest.custom_matchers.setup.ts
  tests/DateFallback.test.ts
  tests/Recurrence.test.ts
  tests/Task.test.ts
Labels: type: internal

#1943 feat: Add new priorities: highest and lowest
  docs/Advanced/Quickadd.md
  docs/Advanced/Styling.md
  docs/Advanced/Urgency.md
  docs/Getting Started/Auto-Suggest.md
  docs/Getting Started/Priority.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Quick Reference.md
  docs/Reference/Task Formats/Dataview Format.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  resources/sample_vaults/Tasks-Demo/.obsidian/snippets/tasks-plugin-priority-as-checkbox-color.css
  src/Query/Filter/PriorityField.ts
  src/Suggestor/Suggestor.ts
  src/Task.ts
  src/TaskLineRenderer.ts
  src/TaskSerializer/DataviewTaskSerializer.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/Urgency.ts
  src/ui/EditTask.svelte
  styles.css
  tests/Query/Filter/PriorityField.test.ts
  tests/Query/Urgency.test.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.ts
  tests/TaskSerializer/DataviewTaskSerializer.test.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
  tests/TaskSerializer/TaskSerializer.test.ts
Labels: scope: emojis and signifiers

#1984 feat: Update Urgency for Lowest to make linear
  docs/Advanced/Styling.md
  docs/Advanced/Urgency.md
  docs/images/tasks-plugin-priority-as-checkbox-color-snippet.png
  resources/sample_vaults/Tasks-Demo/.obsidian/snippets/tasks-plugin-complete-example.css
  resources/sample_vaults/Tasks-Demo/Styling/Sample Tasks for Styling Documentation.md
  src/Urgency.ts
  tests/Query/Urgency.test.ts
Labels: scope: emojis and signifiers

#1987 feat: All settings sections now link to their docs
  docs/images/settings-auto-suggest-task-content.png
  docs/images/settings-optional-date-fields.png
  docs/images/settings-provide-access-keys-in-dialogs.png
  docs/images/settings-recurrence-location.png
  src/Config/SettingsTab.ts
Labels: scope: documentation, scope: user interface

#1988 chore(deps-dev): Bump jest packages to latest
  package.json
  yarn.lock
Labels: dependencies, javascript

#1990 chore(deps-dev): bump typescript from 4.7.4 to 5.0.4
  package.json
  tsconfig.json
  yarn.lock
Labels: dependencies, javascript

#1993 chore(deps-dev): bump eslint to 8.41.0, eslint-plugin-import to 2.27.5
  package.json
  yarn.lock
Labels: dependencies, javascript

#1996 fix: Enable 'High priority' to be selected easily in Auto Suggest
  docs/Getting Started/Auto-Suggest.md
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.ts
Labels: scope: auto-suggest
