Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-06, with the labels that each got.

#2011 chore: Automate content generation of some Priority docs
  docs/Reference/Task Formats/Dataview Format.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  resources/sample_vaults/Tasks-Demo/Formats/Dataview Format.md
  resources/sample_vaults/Tasks-Demo/Formats/Tasks Format.md
  src/Query/Filter/PriorityField.ts
  src/Task.ts
  tests/Query/Filter/PriorityField.test.ts
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Priorities_dataview-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Priorities_dataview-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Priorities_tasksPluginEmoji-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Priorities_tasksPluginEmoji-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.ts
  tests/TestingTools/VerifyMarkdownTable.ts
Labels: scope: documentation, type: internal

#2013 test: Add TaskBuilder.createFullyPopulatedTask()
  src/Recurrence.ts
  src/Status.ts
  src/StatusConfiguration.ts
  src/Task.ts
  tests/Status.test.ts
  tests/StatusConfiguration.test.ts
  tests/Task.test.ts
  tests/TestingTools/TaskBuilder.test.ts
  tests/TestingTools/TaskBuilder.ts
Labels: type: internal

#2028 feat: Add custom grouping, with 'group by function' option
  docs/Introduction.md
  docs/Queries/Grouping.md
  docs/Scripting/About Scripting.md
  docs/Scripting/Custom Grouping.md
  docs/Scripting/Expressions.md
  docs/Scripting/Task Properties.md
  resources/sample_vaults/Tasks-Demo/Functions/Fields for Functions - Demo.md
  src/Query/Filter/FunctionField.ts
  src/Query/Filter/HappensDateField.ts
  src/Query/FilterParser.ts
  src/Query/GroupingTreeNode.ts
  src/Scripting/Expression.ts
  src/Task.ts
  tests/CustomMatchers/CustomMatchersForGrouping.ts
  tests/Query.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.blockLink_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.blockLink_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.created_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.created_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.description_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.description_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.done_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.done_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.due_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.due_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.happens_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.happens_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.priority_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.priority_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.scheduled_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.scheduled_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.start_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.start_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.name_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.name_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.nextStatusSymbol_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.nextStatusSymbol_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.symbol_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.symbol_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.type_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.status.type_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.tags_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.tags_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.urgency_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.urgency_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.ts
  tests/Query/Filter/ReferenceDocs/FilterReference/VerifyFunctionFieldSamples.ts
  tests/Scripting/Expression.test.Expression_result.approved.md
  tests/Scripting/Expression.test.ts
  tests/Scripting/ScriptingTestHelpers.ts
  tests/Scripting/TaskProperties.test.task_dates.approved.md
  tests/Scripting/TaskProperties.test.task_file_properties.approved.md
  tests/Scripting/TaskProperties.test.task_other_fields.approved.md
  tests/Scripting/TaskProperties.test.task_status.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Task.test.ts
  tests/TestHelpers.ts
  tests/TestingTools/ApprovalTestHelpers.ts
Labels: scope: grouping

#2032 feat: Add TasksDate class for use in 'group by function'
  docs/Queries/Grouping.md
  docs/Scripting/Task Properties.md
  src/Query/Filter/HappensDateField.ts
  src/Scripting/TasksDate.ts
  src/Task.ts
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.created_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.created_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.done_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.done_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.due_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.due_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.happens_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.happens_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.scheduled_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.scheduled_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.start_docs.approved.md
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.start_results.approved.txt
  tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.ts
  tests/Scripting/ScriptingTestHelpers.ts
  tests/Scripting/TaskProperties.test.task_dates.approved.md
  tests/Scripting/TasksDate.test.ts
  tests/Task.test.ts
Labels: scope: grouping, scope: reminders

#2033 docs: Add Scripting column to Quick Reference, showing property names
  docs/Quick Reference.md
Labels: scope: documentation

#2046 fix!!: 'group by urgency' now puts most urgent tasks first, not last
  docs/Queries/Grouping.md
  src/Query/Filter/UrgencyField.ts
  tests/Query/Filter/UrgencyField.test.ts
Labels: scope: grouping

#2045 feat: 'group by status.type' names are now more readable
  docs/Queries/Grouping.md
  src/Query/Filter/StatusTypeField.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Status_Transitions_status-types.approved.md
  tests/Query/Filter/StatusTypeField.test.ts
  tests/TaskGroups.test.ts
Labels: scope: grouping

#2056 test: set date in TaskProperties.test.ts to fix failing test
  tests/Scripting/TaskProperties.test.ts
Labels: type: internal

#2058 refactor: Extract generic class QueryComponentOrError
  src/Query/Filter/FilterOrErrorMessage.ts
  src/Query/QueryComponentOrError.ts
Labels: type: internal

#2063 refactor: Reduce complexity in QueryRenderChild.render()
  src/QueryRenderer.ts
Labels: type: internal

#2064 refactor: Introduce QueryResult class
  src/IQuery.ts
  src/Query/Query.ts
  src/Query/QueryResult.ts
  src/QueryRenderer.ts
  tests/Config/DebugSettings.test.ts
  tests/Query.test.ts
  tests/Query/QueryResult.test.ts
Labels: type: internal

#2072 fix: Prevent date components of Urgency changing and midday
  src/Urgency.ts
  tests/Query/Urgency.test.ts
Labels: scope: urgency
