Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-09, with the labels that each got.

#2244 fix: Prevent auto-suggest appearing before the end of the checkbox
  src/Suggestor/EditorSuggestorPopup.ts
  src/Suggestor/Suggestor.ts
  src/Task.ts
  tests/Suggestor/Suggestor.test.ts
Labels: scope: auto-suggest

#2251 test: enable combination-testing of async code
  contributing/Testing/Approval Tests.md
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify2.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify3.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify4.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify5.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify6.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify7.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify8.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.CombinationApprovalsAsync_verify9.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.demonstrate_async_combination_approvals_documentation_example.approved.txt
  tests/TestingTools/CombinationApprovalsAsync.test.ts
  tests/TestingTools/CombinationApprovalsAsync.ts
  tests/TestingTools/RunCombinations.ts
Labels: type: internal

#2253 test: Refactoring to simplify EditTask.test.ts
  tests/EditTask.test.ts
Labels: type: internal

#2272 test: Add exhaustive testing of 'Edit task modal' under wide range of scenarios
  tests/EditTask.test.Exhaustive_editing_Edit_and_save_All_inputs.approved.txt
  tests/EditTask.test.ts
Labels: type: internal

#2264 fix: Editing a checkbox line with empty description now adds creation date, if enabled
  src/Commands/CreateOrEditTaskParser.ts
  tests/Commands/CreateOrEditTaskParser.test.ts
  tests/EditTask.test.Exhaustive_editing_Edit_and_save_All_inputs.approved.txt
Labels: scope: edit task

#2274 fix: 'Create or edit task' now adds Created date if adding global filter
  src/Commands/CreateOrEditTaskParser.ts
  tests/Commands/CreateOrEditTaskParser.test.ts
  tests/EditTask.test.Exhaustive_editing_Edit_and_save_All_inputs.approved.txt
Labels: scope: edit task

#2215 refactor: Introduce GlobalQuery class: the plugin uses a singleton.
  src/Config/GlobalQuery.ts
  src/Config/Settings.ts
  src/Config/SettingsTab.ts
  src/QueryRenderer.ts
  src/lib/QueryRendererHelper.ts
  src/main.ts
  tests/Config/GlobalQuery.test.ts
  tests/Query/Explain/DocsSamplesForExplain.test.ts
  tests/TestingTools/ApprovalTestHelpers.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: type: internal, scope: global query

#2277 chore: Fix error TS5055: Cannot write file ...tests/global-setup.js
  .gitignore
  tsconfig.json
Labels: type: internal

#2279 refactor: Remove recently-added cyclic dependencies.
  src/Config/Settings.ts
Labels: type: internal

#2282 refactor: Separate settings out of GlobalFilter
  src/Config/GlobalFilter.ts
  src/Config/SettingsTab.ts
  src/main.ts
  tests/GlobalFilter.test.ts
  tests/Task.test.ts
  tests/TaskLineRenderer.test.ts
Labels: type: internal, scope: global filter

#2280 refactor: remove unused return value in `createTasksList()`
  src/QueryRenderer.ts
Labels: type: internal, scope: rendering of tasks

#2283 refactor: Add getInstance() to GlobalFilter & make all else non-static
  src/Commands/CreateOrEditTaskParser.ts
  src/Config/GlobalFilter.ts
  src/Config/SettingsTab.ts
  src/File.ts
  src/InlineRenderer.ts
  src/Query/Filter/DescriptionField.ts
  src/Suggestor/Suggestor.ts
  src/Task.ts
  src/TaskLineRenderer.ts
  src/lib/QueryRendererHelper.ts
  src/main.ts
  src/ui/EditTask.svelte
  tests/Commands/CreateOrEditTaskParser.test.ts
  tests/Commands/ToggleDone.test.ts
  tests/EditTask.test.ts
  tests/GlobalFilter.test.ts
  tests/Query.test.ts
  tests/Query/Filter/DescriptionField.test.ts
  tests/Query/Filter/TagsField.test.ts
  tests/Suggestor/Suggestor.test.ts
  tests/Task.test.ts
  tests/TaskLineRenderer.test.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: type: internal, scope: global filter

#2286 refactor: Convert one use of GlobalFilter.getInstance() to instance
  src/QueryRenderer.ts
  src/lib/QueryRendererHelper.ts
  tests/Query/Explain/DocsSamplesForExplain.test.ts
  tests/TestingTools/ApprovalTestHelpers.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: type: internal, scope: rendering of tasks, scope: global filter

#2288 feat: Scripting enables removing file extension from path and filename properties
  docs/Introduction.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Scripting/Query Properties.md
  docs/Scripting/Task Properties.md
  src/Scripting/TasksFile.ts
  tests/Scripting/QueryProperties.test.query_file_properties.approved.md
  tests/Scripting/QueryProperties.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.filename_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.filename_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/TaskProperties.test.task_file_properties.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Scripting/TasksFile.test.ts
Labels: scope: scripting

#2285 feat: 'group by backlink' headings link to location & show hover previews
  docs/Queries/Grouping.md
  src/Query/Filter/BacklinkField.ts
  tests/Query/Filter/BacklinkField.test.ts
Labels: scope: grouping, scope: backlinks

#2284 refactor: remove cyclic dependencies & optional parameter in `TaskLineRenderer.ts`
  src/InlineRenderer.ts
  src/QueryRenderer.ts
  src/Task.ts
  src/TaskLineRenderer.ts
Labels: type: internal, scope: rendering of tasks

#2292 refactor: remove destructured types in Query.ts
  src/Config/GlobalQuery.ts
  src/Query/Query.ts
  src/lib/QueryRendererHelper.ts
  tests/Config/DebugSettings.test.ts
  tests/Query.test.ts
  tests/Query/Filter/DueDateField.test.ts
  tests/Query/Filter/TextField.test.ts
  tests/TestingTools/ApprovalTestHelpers.ts
  tests/TestingTools/FilterTestHelpers.ts
  tests/lib/QueryRendererHelper.test.ts
Labels: type: internal

#2295 chore: automate detection of circular code dependencies
  .github/workflows/verify.yml
  .gitignore
  contributing/Code/About Code.md
  contributing/Code/How do I see circular dependencies.md
  contributing/Code/circular-deps.svg
  package.json
  yarn.lock
Labels: type: internal

#2065 chore: Specify supported node versions in package.json
  package.json
Labels: type: internal

#2300 refactor: move code for task counts text to QueryResult
  src/Query/QueryResult.ts
  src/QueryRenderer.ts
  tests/Query/QueryResult.test.ts
Labels: type: internal, scope: rendering of tasks

#2301 feat: 'show task count' now shows total, if 'limit' applied
  docs/Queries/Limiting.md
  src/Query/Query.ts
  src/Query/QueryResult.ts
  tests/Query.test.ts
  tests/Query/QueryResult.test.ts
Labels: scope: rendering of tasks

#2303 fix: Prevent crash at startup if user never previously edited settings
  src/main.ts
Labels: scope: start-up

#2308 feat: Add task.priorityNameGroupText and task.status.typeGroupText
  docs/Introduction.md
  docs/Queries/Grouping.md
  docs/Quick Reference.md
  docs/Scripting/Task Properties.md
  src/Query/Filter/PriorityField.ts
  src/Query/Filter/StatusTypeField.ts
  src/Status.ts
  src/Task.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.priorityName_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.priorityName_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.statuses_task.status.type_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.statuses_task.status.type_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/TaskProperties.test.task_other_fields.approved.md
  tests/Scripting/TaskProperties.test.task_status.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Status.test.ts
Labels: scope: grouping, scope: scripting
