Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2023-08, with the labels that each got.

#2193 feat: Add + sign to supported list markers
  docs/Getting Started/Auto-Suggest.md
  docs/Getting Started/Getting Started.md
  docs/Introduction.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
  src/Task.ts
  tests/Task.test.ts
Labels: scope: parsing markdown

#2186 feat: New date options: 'on or before', 'on or after', 'in or before' & 'in or after'
  docs/Introduction.md
  docs/Queries/Filters.md
  docs/Quick Reference.md
  src/Query/Filter/DateField.ts
  tests/Query/Filter/DueDateField.test.ts
Labels: type: enhancement, scope: filters

#2201 fix: Single # symbol in task line no longer treated as a tag
  src/Task.ts
  tests/Query/Filter/TagsField.test.ts
  tests/Task.test.ts
Labels: scope: tags

#2202 docs: Add a Tags page, to help with FAQs
  docs/Getting Started/Tags.md
  docs/Queries/Filters.md
  docs/Queries/Grouping.md
  docs/Queries/Layout.md
  docs/Queries/Sorting.md
  src/Task.ts
Labels: scope: documentation, scope: tags

#2203 fix: Remove verbose debug console output
  src/Cache.ts
  src/LivePreviewExtension.ts
  src/QueryRenderer.ts
Labels: scope: logging

#2207 vault: update smoke test for recent code changes
  resources/sample_vaults/Tasks-Demo/Manual Testing/Styling of Queries.md
Labels: type: internal, needs-smoke-test

#2226 refactor: split getComponentClassesAndData() in to 2 functions
  src/TaskLineRenderer.ts
Labels: type: internal, scope: rendering of tasks

#2233 test: Add tests for logic in EditorSuggestor.onTrigger()
  src/Suggestor/EditorSuggestorPopup.ts
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.ts
Labels: type: internal

#2234 refactor: remove unused parameter from `TaskLayout` constructor
  src/TaskLayout.ts
Labels: type: internal
