Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2024-07, with the labels that each got.

#2928 docs: fixed a minor typo
  docs/Queries/Grouping.md
Labels: scope: documentation

#2940 feat: Experimental access to raw frontmatter in query.file & task.file
  resources/sample_vaults/Tasks-Demo/.obsidian/appearance.json
  resources/sample_vaults/Tasks-Demo/.obsidian/community-plugins.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/js-engine/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/js-engine/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/js-engine/styles.css
  resources/sample_vaults/Tasks-Demo/.obsidian/snippets/js-engine-code-block-border.css
  resources/sample_vaults/Tasks-Demo/.obsidian/types.json
  resources/sample_vaults/Tasks-Demo/How To/Access properties in frontmatter.md
  resources/sample_vaults/Tasks-Demo/How To/Find tasks in notes with particular tag.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Frontmatter code.canvas
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Tags in Frontmatter.md
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_complex_example.md
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_complex_example_standardised.md
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_custom_number_property.md
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_tags_with_two_values_on_one_line.md
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_tags_with_two_values_on_two_lines.md
  src/Obsidian/Cache.ts
  src/Scripting/TasksFile.ts
  tests/Obsidian/__test_data__/yaml_complex_example.ts
  tests/Obsidian/__test_data__/yaml_complex_example_standardised.ts
  tests/Obsidian/__test_data__/yaml_custom_number_property.ts
  tests/Obsidian/__test_data__/yaml_tags_with_two_values_on_one_line.ts
  tests/Obsidian/__test_data__/yaml_tags_with_two_values_on_two_lines.ts
  tests/Scripting/TasksFile.test.ts
  tests/ui/EditableTask.test.ts
Labels: scope: filters, scope: parsing markdown, scope: scripting

#2945 fix: Tasks search results now render correctly in Tabs plugin
  src/Renderer/QueryRenderer.ts
Labels: scope: rendering of tasks

#2949 feat: improve access to tags
  resources/sample_vaults/Tasks-Demo/_meta/templater_scripts/convert_test_data_markdown_to_js.js
  src/Scripting/TasksFile.ts
  tests/Obsidian/__test_data__/blockquote.ts
  tests/Obsidian/__test_data__/callout.ts
  tests/Obsidian/__test_data__/callout_custom.ts
  tests/Obsidian/__test_data__/callout_labelled.ts
  tests/Obsidian/__test_data__/callouts_nested_issue_2890_labelled.ts
  tests/Obsidian/__test_data__/callouts_nested_issue_2890_unlabelled.ts
  tests/Obsidian/__test_data__/comments_html_style.ts
  tests/Obsidian/__test_data__/comments_markdown_style.ts
  tests/Obsidian/__test_data__/empty_yaml.ts
  tests/Obsidian/__test_data__/example_kanban.ts
  tests/Obsidian/__test_data__/inheritance_1parent1child.ts
  tests/Obsidian/__test_data__/inheritance_1parent1child1newroot_after_header.ts
  tests/Obsidian/__test_data__/inheritance_1parent1child1sibling_emptystring.ts
  tests/Obsidian/__test_data__/inheritance_1parent2children.ts
  tests/Obsidian/__test_data__/inheritance_1parent2children1grandchild.ts
  tests/Obsidian/__test_data__/inheritance_1parent2children1sibling.ts
  tests/Obsidian/__test_data__/inheritance_1parent2children2grandchildren.ts
  tests/Obsidian/__test_data__/inheritance_1parent2children2grandchildren1sibling.ts
  tests/Obsidian/__test_data__/inheritance_1parent2children2grandchildren1sibling_start_with_heading.ts
  tests/Obsidian/__test_data__/inheritance_2siblings.ts
  tests/Obsidian/__test_data__/inheritance_listitem_task.ts
  tests/Obsidian/__test_data__/inheritance_listitem_task_siblings.ts
  tests/Obsidian/__test_data__/inheritance_task_2listitem_3task.ts
  tests/Obsidian/__test_data__/inheritance_task_listitem.ts
  tests/Obsidian/__test_data__/inheritance_task_listitem_mixed_grandchildren.ts
  tests/Obsidian/__test_data__/inheritance_task_listitem_task.ts
  tests/Obsidian/__test_data__/inheritance_task_mixed_children.ts
  tests/Obsidian/__test_data__/link_in_file_body.ts
  tests/Obsidian/__test_data__/link_in_file_body_with_custom_display_text.ts
  tests/Obsidian/__test_data__/link_in_heading.ts
  tests/Obsidian/__test_data__/link_in_yaml.ts
  tests/Obsidian/__test_data__/link_is_broken.ts
  tests/Obsidian/__test_data__/list_statuses.ts
  tests/Obsidian/__test_data__/list_styles.ts
  tests/Obsidian/__test_data__/multi_line_task_and_list_item.ts
  tests/Obsidian/__test_data__/multiple_headings.ts
  tests/Obsidian/__test_data__/no_heading.ts
  tests/Obsidian/__test_data__/no_yaml.ts
  tests/Obsidian/__test_data__/one_task.ts
  tests/Obsidian/__test_data__/yaml_1_alias.ts
  tests/Obsidian/__test_data__/yaml_2_aliases.ts
  tests/Obsidian/__test_data__/yaml_complex_example.ts
  tests/Obsidian/__test_data__/yaml_complex_example_standardised.ts
  tests/Obsidian/__test_data__/yaml_custom_number_property.ts
  tests/Obsidian/__test_data__/yaml_tags_field_added_by_obsidian_but_not_populated.ts
  tests/Obsidian/__test_data__/yaml_tags_had_value_then_was_emptied_by_obsidian.ts
  tests/Obsidian/__test_data__/yaml_tags_has_multiple_values.ts
  tests/Obsidian/__test_data__/yaml_tags_is_empty.ts
  tests/Obsidian/__test_data__/yaml_tags_is_empty_list.ts
  tests/Obsidian/__test_data__/yaml_tags_with_one_value_on_new_line.ts
  tests/Obsidian/__test_data__/yaml_tags_with_one_value_on_single_line.ts
  tests/Obsidian/__test_data__/yaml_tags_with_two_values_on_one_line.ts
  tests/Obsidian/__test_data__/yaml_tags_with_two_values_on_two_lines.ts
  tests/Scripting/TasksFile.test.ts
  tests/__mocks__/obsidian.ts
  tests/ui/EditableTask.test.ts
Labels: scope: parsing markdown

#2948 docs: Fix first task example in Getting Started
  docs/Getting Started/Getting Started.md
Labels: scope: documentation

#2951 fix: Prevent task.frontmatter.tags being null if no tags in frontmatter
  resources/sample_vaults/Tasks-Demo/How To/Find tasks in notes with particular tag.md
  src/Scripting/TasksFile.ts
  tests/Scripting/TasksFile.test.ts
  tests/__mocks__/obsidian.ts
Labels: scope: parsing markdown

#2970 refactor: remove nesting in `Recurrence.next()`
  src/Task/Recurrence.ts
Labels: type: internal, scope: recurrence

#2973 chore: Add Ilyas Landikov as co-author of Tasks
  LICENSE
  esbuild.config.mjs
  manifest.json
  package.json
Labels: type: internal

#2974 fix: Prevent task.frontmatter.tags being null if no frontmatter
  resources/sample_vaults/Tasks-Demo/How To/Access properties in frontmatter.md
  resources/sample_vaults/Tasks-Demo/How To/Find tasks in notes with particular tag.md
  resources/sample_vaults/Tasks-Demo/_meta/templater_scripts/convert_test_data_markdown_to_js.js
  src/Scripting/TasksFile.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/Cache.test.ts
  tests/Scripting/TasksFile.test.ts
  tests/TestingTools/MockDataHelpers.ts
  tests/ui/EditableTask.test.ts
Labels: scope: parsing markdown

#2976 contrib: add documentation on testing code that uses Obsidian API
  contributing/Testing/About Testing.md
  contributing/Testing/Using Obsidian API in tests.md
  tests/Obsidian/Cache.test.ts
Labels: scope: documentation

#2975 refactor: extract `nextOccurrence()` method and reuse it
  src/Task/Recurrence.ts
Labels: type: internal, scope: recurrence

#2981 test: demo property custom searches
  resources/sample_vaults/Tasks-Demo/.obsidian/types.json
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_all_property_types_empty.md
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_all_property_types_populated.md
  tests/Obsidian/Cache.test.ts
  tests/Obsidian/SimulatedFile.ts
  tests/Obsidian/__test_data__/yaml_all_property_types_empty.ts
  tests/Obsidian/__test_data__/yaml_all_property_types_populated.ts
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.obsidian_properties_task.file.frontmatter_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.obsidian_properties_task.file.frontmatter_results.approved.txt
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.obsidian_properties_task.file.frontmatter_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.obsidian_properties_task.file.frontmatter_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/TasksFile.test.TasksFile_-_reading_frontmatter_should_read_yaml_all_property_types_empty.approved.json
  tests/Scripting/TasksFile.test.TasksFile_-_reading_frontmatter_should_read_yaml_all_property_types_populated.approved.json
  tests/Scripting/TasksFile.test.ts
Labels: type: internal

#2980 refactor: move `referenceDate` field to `Occurrence` class
  src/Task/Recurrence.ts
Labels: type: internal, scope: recurrence

#2985 refactor: move `Occurrence` class separate to a separate file and minor improvements
  src/Suggestor/Suggestor.ts
  src/Task/Occurrence.ts
  src/Task/Recurrence.ts
  src/Task/Task.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/ui/EditableTask.ts
  tests/Task/Recurrence.test.ts
  tests/TestingTools/RecurrenceBuilder.ts
  tests/TestingTools/SampleTasks.ts
  tests/TestingTools/TaskBuilder.ts
Labels: type: internal

#2991 feat: releasable code for accessing properties via `task.file`
  resources/sample_vaults/Tasks-Demo/Test Data/yaml_capitalised_property_name.md
  src/Scripting/TasksFile.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/__test_data__/yaml_capitalised_property_name.ts
  tests/Scripting/TasksFile.test.ts
Labels: scope: parsing markdown, scope: scripting

#2992 refactor: simplify `Task.handleNewStatus()`
  src/Task/Task.ts
Labels: type: internal, scope: recurrence

#2997 Docs access properties
  docs/Getting Started/About Getting Started.md
  docs/Getting Started/Frontmatter Properties.md
  docs/Scripting/Task Properties.md
  docs/What is New?/Changelog.md
  resources/sample_vaults/Tasks-Demo/.obsidian/types.json
  resources/sample_vaults/Tasks-Demo/Test Data/docs_sample_for_task_properties_reference.md
  src/Scripting/TasksFile.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/__test_data__/docs_sample_for_task_properties_reference.ts
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.obsidian_properties_task.file.frontmatter_docs.approved.md
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.obsidian_properties_task.file.frontmatter_results.approved.txt
  tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.obsidian_properties_task.file.frontmatter_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.obsidian_properties_task.file.frontmatter_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
  tests/Scripting/ScriptingTestHelpers.ts
  tests/Scripting/TaskProperties.test.task_frontmatter_properties.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Scripting/TasksFile.test.ts
  tests/ui/EditableTask.test.ts
Labels: scope: documentation, scope: parsing markdown
