Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2024-11, with the labels that each got.

#3164 refactor: test `DateEditor` svelte component
  src/ui/DateEditor.svelte
  tests/ui/DateEditor.test.ts
  tests/ui/DateEditorWrapper.svelte
  tests/ui/EditTask.test.ts
  tests/ui/RenderingTestHelpers.ts
Labels: type: internal, scope: edit task

#3166 fix: '\' at end of last line in query no longer discards the instruction
  src/Query/Scanner.ts
  tests/Query/Query.test.ts
  tests/Query/Scanner.test.ts
Labels: scope: filters

#3165 refactor: add `PriorityTools.priorityValue()`
  src/TaskSerializer/DataviewTaskSerializer.ts
  src/lib/PriorityTools.ts
  src/ui/EditableTask.ts
  tests/lib/PriorityTools.test.ts
Labels: type: internal

#3169 feat: Add date-picker to the Edit Task modal
  src/ui/DateEditor.svelte
  src/ui/EditTask.scss
  tests/ui/DateEditor.test.ts
  tests/ui/DateEditorWrapper.svelte
  tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
  tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
  tests/ui/EditTask.test.ts
  tests/ui/RenderingTestHelpers.ts
Labels: scope: edit task

#3186 feat: Add date-picker to Reading Mode and Tasks query results
  resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
  src/Renderer/TaskLineRenderer.ts
  src/ui/Menus/DatePicker.ts
  tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
Labels: scope: user interface

#3189 refactor: Remove unused Flatpickr code from Edit Task modal
  src/Obsidian/TaskModal.ts
  src/ui/EditTask.svelte
  tests/ui/EditTask.test.ts
Labels: scope: edit task

#3190 test: - Capture string representation of emoji-parsing regexes
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
Labels: type: internal

#3191 fix: - Allow multiple spaces after onCompletion emoji
  src/TaskSerializer/DefaultTaskSerializer.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
Labels: scope: parsing markdown, scope: lifecycle of tasks

#3192 Refactor emoji parsing
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/lib/StringHelpers.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
  tests/lib/StringHelpers.test.ts
Labels: type: internal, scope: parsing markdown

#3193 fix: Handle any hidden VS16 character on all emojis
  src/TaskSerializer/DefaultTaskSerializer.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
Labels: scope: parsing markdown

#3195 test: Add some example code to explore accessing links
  resources/sample_vaults/Tasks-Demo/Test Data/link_in_task_html.md
  resources/sample_vaults/Tasks-Demo/Test Data/link_in_task_markdown_link.md
  resources/sample_vaults/Tasks-Demo/Test Data/link_in_task_wikilink.md
  resources/sample_vaults/Tasks-Demo/Test Data/links_everywhere.md
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/Cache.test.ts
  tests/Obsidian/__test_data__/link_in_task_html.json
  tests/Obsidian/__test_data__/link_in_task_markdown_link.json
  tests/Obsidian/__test_data__/link_in_task_wikilink.json
  tests/Obsidian/__test_data__/links_everywhere.json
Labels: type: internal, scope: parsing markdown

#3199 docs: Collapse some long HTML samples in callouts
  docs/Advanced/Styling.md
  docs/snippets-embedded-in-multiple-pages/Sample HTML - Full mode.md
  docs/snippets-embedded-in-multiple-pages/Sample HTML - Short mode.md
  package.json
Labels: scope: documentation

#3200 docs: Add page on editing dates
  docs/Editing/About Editing.md
  docs/Editing/Editing Dates.md
  docs/What is New/Changelog.md
  docs/images/date-context-menu-1.png
  docs/images/date-context-menu-2.png
  docs/images/date-picker-1.png
  docs/images/date-picker-2.png
Labels: scope: documentation
