Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2024-08, with the labels that each got.

#3001 docs: more work on properties documentation
  docs/Getting Started/Frontmatter Properties.md
  docs/Getting Started/Tags.md
  docs/Quick Reference.md
  docs/Scripting/Task Properties.md
  resources/sample_vaults/Tasks-Demo/How To/Access properties in frontmatter.md
  resources/sample_vaults/Tasks-Demo/How To/Find tasks in notes with particular tag.md
Labels: scope: documentation, scope: parsing markdown

#3003 fix: Editing properties/frontmatter now updates Query results
  src/Scripting/TasksFile.ts
  src/Task/Task.ts
  tests/Scripting/TasksFile.test.ts
  tests/Task/Task.test.ts
  tests/TestingTools/TaskBuilder.test.ts
  tests/TestingTools/TaskBuilder.ts
Labels: scope: parsing markdown

#3005 fix: Tasks in renamed files forgot about any properties/frontmatter values in the file
  src/Obsidian/Cache.ts
  src/Task/DateFallback.ts
  tests/Task/DateFallback.test.ts
Labels: scope: parsing markdown

#2840 feat: New "On Completion" field with support for Delete automatic action
  .gitattributes
  docs/Advanced/Styling.md
  docs/Getting Started/About Getting Started.md
  docs/Getting Started/On Completion.md
  docs/How To/Find tasks with invalid data.md
  docs/Reference/Task Formats/Dataview Format.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  docs/Scripting/Task Properties.md
  src/Commands/CreateOrEditTaskParser.ts
  src/Layout/TaskLayoutOptions.ts
  src/Renderer/TaskFieldRenderer.ts
  src/Task/OnCompletion.ts
  src/Task/Task.ts
  src/TaskSerializer/DataviewTaskSerializer.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/TaskSerializer/index.ts
  src/ui/EditableTask.ts
  tests/CustomMatchers/CustomMatchersForTaskSerializer.ts
  tests/DocumentationSamples/ValidateTasks.test.validate-tasks_all-emojis-emojis.approved.text
  tests/DocumentationSamples/ValidateTasks.test.validate-tasks_find-unread-emojis.approved.text
  tests/Layout/TaskLayout.test.ts
  tests/Layout/TaskLayoutOptions.test.ts
  tests/Query/Query.test.ts
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
  tests/Renderer/TaskLineRenderer.test.ts
  tests/Scripting/TaskProperties.test.task_other_fields.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Task/OnCompletion.test.ts
  tests/Task/OnCompletion.test.visualise_completion-behaviour_visualise.approved.txt
  tests/Task/Task.test.ts
  tests/TaskSerializer/DataviewTaskSerializer.test.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Emojis_tabulate-emojis.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_dataview-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_dataview-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_tasksPluginEmoji-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_tasksPluginEmoji-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.ts
  tests/TaskSerializer/TaskSerializer.test.ts
  tests/TestingTools/SampleTasks.ts
  tests/TestingTools/TaskBuilder.test.ts
  tests/TestingTools/TaskBuilder.ts
  tests/ui/EditableTask.test.ts
Labels: scope: managing tasks, scope: lifecycle of tasks, priority: high

#3008 fix: collect root `ListItem`s
  resources/sample_vaults/Tasks-Demo/Test Data/inheritance_2roots_listitem_listitem_task.md
  resources/sample_vaults/Tasks-Demo/Test Data/inheritance_listitem_listitem_task.md
  src/Obsidian/Cache.ts
  src/Task/ListItem.ts
  tests/Obsidian/Cache.test.ts
  tests/Obsidian/__test_data__/inheritance_2roots_listitem_listitem_task.ts
  tests/Obsidian/__test_data__/inheritance_listitem_listitem_task.ts
  tests/Task/ListItem.test.ts
Labels: type: internal, scope: sub-tasks and super-tasks

#3010 refactor: Small improvements to the 'On Completion' implementation
  src/Task/OnCompletion.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  src/ui/EditableTask.ts
  tests/Task/OnCompletion.test.ts
  tests/Task/Task.test.ts
  tests/TaskSerializer/DataviewTaskSerializer.test.ts
  tests/TaskSerializer/DefaultTaskSerializer.test.ts
  tests/TestingTools/SampleTasks.ts
  tests/TestingTools/TaskBuilder.ts
  tests/ui/EditTask.test.ts
Labels: type: internal

#3015 refactor: Refactor On Completion code and tests
  src/Task/OnCompletion.ts
  src/TaskSerializer/DefaultTaskSerializer.ts
  tests/Task/OnCompletion.test.ts
Labels: type: internal, scope: lifecycle of tasks

#3016 feat: Add 'keep' option to 'On Completion'
  docs/Getting Started/On Completion.md
  docs/Reference/Task Formats/Dataview Format.md
  docs/Reference/Task Formats/Tasks Emoji Format.md
  src/Task/OnCompletion.ts
  tests/Task/OnCompletion.test.ts
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_dataview-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_dataview-snippet.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_tasksPluginEmoji-include.approved.md
  tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_tasksPluginEmoji-snippet.approved.md
  tests/TestingTools/SampleTasks.ts
Labels: scope: lifecycle of tasks

#3018 refactor: add `QueryResultsRenderer` class
  src/Renderer/QueryRenderer.ts
  src/Renderer/QueryResultsRenderer.ts
Labels: type: internal, scope: rendering of tasks

#3020 fix: Various improvements to cursor positions in Auto-Suggest
  docs/Editing/Auto-Suggest.md
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.ts
Labels: scope: auto-suggest

#3022 refactor: introduce parameter object to functions in Suggestor.ts
  src/Suggestor/Suggestor.ts
Labels: type: internal, scope: auto-suggest

#3023 refactor: Make the Auto Suggest code a bit easier to maintain
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_correct_options_for_partial_due_date_lines.approved.txt
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_correct_options_for_partial_recurrence_lines.approved.txt
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_correct_options_for_partial_due_date_lines.approved.txt
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_correct_options_for_partial_recurrence_lines.approved.txt
  tests/Suggestor/Suggestor.test.ts
Labels: type: internal, scope: auto-suggest

#3025 fix: Better dataview space & cursor in date suggestions
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_correct_options_for_partial_due_date_lines.approved.txt
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_correct_options_for_partial_due_date_lines.approved.txt
Labels: scope: auto-suggest

#3027 refactor: remove `QueryResultsRenderer` inheritance
  src/Renderer/QueryRenderer.ts
  src/Renderer/QueryResultsRenderer.ts
Labels: type: internal, scope: rendering of tasks

#3028 feat: Teach Auto Suggest to support "On Completion"
  docs/Editing/Auto-Suggest.md
  docs/Getting Started/On Completion.md
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
  tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
  tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
  tests/Suggestor/Suggestor.test.ts
Labels: scope: auto-suggest, scope: lifecycle of tasks

#3029 chore: Fix cloning on Windows (I hope)
  contributing/.obsidian/core-plugins.json
  contributing/Documentation/Redirects - Testing old links still work.md
  docs/.obsidian/core-plugins.json
  docs/What is New/Breaking Changes.md
  docs/What is New/Changelog.md
Labels: type: internal

#3033 Show hide on completion
  docs/Queries/Layout.md
  docs/Quick Reference.md
  docs/Scripting/Task Properties.md
  src/Query/Query.ts
  tests/Query/Query.test.ts
Labels: scope: show/hide

#3036 Border theme support
  docs/Reference/Status Collections/About Status Collections.md
  docs/Reference/Status Collections/Border Theme.md
  docs/What is New/Changelog.md
  docs/images/settings-custom-statuses-initial.png
  docs/images/settings-statuses-initial.png
  docs/images/theme-border-reading-view.png
  resources/sample_vaults/Tasks-Demo/.obsidian/themes/Border/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/themes/Border/theme.css
  resources/sample_vaults/Tasks-Demo/Styling/Theme - Border.md
  src/Config/SettingsTab.ts
  src/Config/Themes/BorderThemeCollection.ts
  src/Config/Themes/index.ts
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Border_Table.approved.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Border_Table.approved.mermaid.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Border_Tasks.approved.md
  tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Border_Text.approved.txt
  tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
Labels: scope: task states

#3037 refactor: Introduce 'DateTime/' sub-directories in 'src/' and 'tests/'
  src/Commands/CreateOrEdit.ts
  src/Commands/CreateOrEditTaskParser.ts
  src/DateTime/DateAbbreviations.ts
  src/DateTime/DateFallback.ts
  src/DateTime/DateParser.ts
  src/DateTime/DateRange.ts
  src/DateTime/DateTools.ts
  src/DateTime/Postponer.ts
  src/DateTime/TasksDate.ts
  src/Obsidian/Cache.ts
  src/Query/Filter/DateField.ts
  src/Query/Filter/FunctionField.ts
  src/Renderer/QueryRenderer.ts
  src/Renderer/QueryResultsRenderer.ts
  src/Suggestor/Suggestor.ts
  src/Task/Occurrence.ts
  src/Task/Task.ts
  src/ui/DateEditor.svelte
  src/ui/EditableTask.ts
  src/ui/Menus/PostponeMenu.ts
  tests/CustomMatchers/CustomMatchersForSorting.ts
  tests/DateTime/DateAbbreviations.test.ts
  tests/DateTime/DateFallback.test.ts
  tests/DateTime/DateParser.test.ts
  tests/DateTime/DateRange.test.ts
  tests/DateTime/DateTools.test.ts
  tests/DateTime/Postponer.test.ts
  tests/DateTime/TasksDate.test.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Renderer/TaskLineRenderer.test.ts
  tests/Scripting/ScriptingTestHelpers.ts
  tests/Task/Task.test.ts
  tests/TestingTools/DateTestHelpers.ts
  tests/TestingTools/RecurrenceBuilder.ts
  tests/TestingTools/TaskBuilder.ts
  tests/lib/TypeDetection.test.ts
  tests/ui/EditTask.test.ts
Labels: type: internal

#3038 feat: Add date picker in Reading mode and Tasks Query results
  esbuild.config.mjs
  package.json
  src/DateTime/DateFieldTypes.ts
  src/DateTime/Postponer.ts
  src/Renderer/Renderer.scss
  src/Renderer/TaskLineRenderer.ts
  src/styles.scss
  src/ui/EditInstructions/DateInstructions.ts
  src/ui/Menus/DatePicker.ts
  src/ui/Menus/PostponeMenu.ts
  tests/DateTime/Postponer.test.ts
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
  tests/ui/EditInstructions/DateInstructions.test.ts
  yarn.lock
Labels: scope: user interface

#3040 refactor: test QueryResultsRenderer
  src/Renderer/QueryRenderer.ts
  src/Renderer/QueryResultsRenderer.ts
  src/Renderer/TaskLineRenderer.ts
  tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html
  tests/Renderer/QueryResultsRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#3045 feat: Add date context menu in Reading mode and Tasks Query results
  src/DateTime/DateFieldTypes.ts
  src/DateTime/Postponer.ts
  src/Renderer/TaskLineRenderer.ts
  src/ui/EditInstructions/DateInstructions.ts
  src/ui/EditInstructions/MenuDividerInstruction.ts
  src/ui/Menus/DateMenu.ts
  src/ui/Menus/TaskEditingMenu.ts
  tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html
  tests/Renderer/QueryResultsRenderer.test.ts
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
  tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
  tests/ui/EditInstructions/DateInstructions.test.ts
  tests/ui/EditInstructions/MenuDividerInstruction.test.ts
  tests/ui/Menus/DateMenu.test.ts
Labels: scope: user interface

#3052 Add modal date picker
  src/Obsidian/TaskModal.ts
  src/ui/DateEditor.svelte
  src/ui/EditTask.scss
  src/ui/EditTask.svelte
  tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
  tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
  tests/ui/EditTask.test.ts
Labels: scope: edit task
