Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2025-02, with the labels that each got.

#3300 feat: Add "Query File Defaults" facility
  docs/Getting Started/Obsidian Properties.md
  docs/Queries/Query File Defaults.md
  docs/Scripting/Placeholders.md
  docs/What is New/Changelog.md
  docs/images/query-file-defaults-file-properties-controls.png
  docs/images/query-file-defaults-meta-bind-controls.png
  docs/snippets-embedded-in-multiple-pages/Meta Bind Query Widgets.md
  resources/sample_vaults/Tasks-Demo/.obsidian/appearance.json
  resources/sample_vaults/Tasks-Demo/.obsidian/community-plugins.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-meta-bind-plugin/data.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-meta-bind-plugin/main.js
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-meta-bind-plugin/manifest.json
  resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-meta-bind-plugin/styles.css
  resources/sample_vaults/Tasks-Demo/.obsidian/snippets/widen-property-labels.css
  resources/sample_vaults/Tasks-Demo/.obsidian/types.json
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Placeholder examples to capture in tests and docs.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Project 1.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Project 2.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Project Search.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/workdate Example.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_false.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_null.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_true.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_ignore_global_query.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_short_mode.md
  src/Query/QueryFileDefaults.ts
  src/Query/QueryRendererHelper.ts
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_meta-bind-widgets-include.approved.md
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_meta-bind-widgets-snippet.approved.md
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_supported-properties-empty.approved.yaml
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_supported-properties-full.approved.yaml
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/__test_data__/query_file_defaults_all_options_false.json
  tests/Obsidian/__test_data__/query_file_defaults_all_options_null.json
  tests/Obsidian/__test_data__/query_file_defaults_all_options_true.json
  tests/Obsidian/__test_data__/query_file_defaults_ignore_global_query.json
  tests/Obsidian/__test_data__/query_file_defaults_short_mode.json
  tests/Query/QueryFileDefaults.test.ts
  tests/Query/QueryRendererHelper.test.ts
Labels: scope: filters, scope: frontmatter

#3301 feat: Simplify 'explain' text
  docs/Queries/Explaining Queries.md
  docs/Queries/Line Continuations.md
  docs/Queries/Regular Expressions.md
  docs/Scripting/Placeholders.md
  src/Query/Explain/Explainer.ts
  tests/Config/DebugSettings.test.ts
  tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_filters-date-examples.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-week-month-quarter-year.approved.explanation.text
  tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-weekday.approved.explanation.text
  tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
  tests/Query/Query.test.ts
  tests/Query/QueryRendererHelper.test.ts
Labels: scope: explain

#3315 refactor: Improve QueryFileDefaults data maintainability
  src/Query/QueryFileDefaults.ts
Labels: type: internal, scope: frontmatter

#3316 refactor: Rename 'tasks_query_*' properties to 'TQ_*'
  docs/Queries/Query File Defaults.md
  docs/images/query-file-defaults-file-properties-controls.png
  docs/snippets-embedded-in-multiple-pages/Meta Bind Query Widgets.md
  resources/sample_vaults/Tasks-Demo/.obsidian/snippets/widen-property-labels.css
  resources/sample_vaults/Tasks-Demo/.obsidian/types.json
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Placeholder examples to capture in tests and docs.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_false.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_null.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_true.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_ignore_global_query.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_short_mode.md
  src/Query/QueryFileDefaults.ts
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_meta-bind-widgets-include.approved.md
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_meta-bind-widgets-snippet.approved.md
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_supported-properties-empty.approved.yaml
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_supported-properties-full.approved.yaml
  tests/Obsidian/__test_data__/query_file_defaults_all_options_false.json
  tests/Obsidian/__test_data__/query_file_defaults_all_options_null.json
  tests/Obsidian/__test_data__/query_file_defaults_all_options_true.json
  tests/Obsidian/__test_data__/query_file_defaults_ignore_global_query.json
  tests/Obsidian/__test_data__/query_file_defaults_short_mode.json
  tests/Query/QueryRendererHelper.test.ts
Labels: scope: frontmatter

#3317 feat: add new command 'Add all Query File Defaults properties'
  docs/Queries/Query File Defaults.md
  docs/images/query-file-defaults-file-properties-controls.png
  resources/sample_vaults/Tasks-Demo/Manual Testing/Frontmatter/Placeholder examples to capture in tests and docs.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_false.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_null.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_file_defaults_all_options_true.md
  src/Commands/AddQueryFileDefaultsProperties.ts
  src/Commands/index.ts
  src/Query/QueryFileDefaults.ts
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_supported-properties-empty.approved.yaml
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_supported-properties-full.approved.yaml
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.ts
  tests/Obsidian/__test_data__/query_file_defaults_all_options_false.json
  tests/Obsidian/__test_data__/query_file_defaults_all_options_null.json
  tests/Obsidian/__test_data__/query_file_defaults_all_options_true.json
  tests/Query/QueryFileDefaults.test.ts
Labels: scope: commands, scope: frontmatter

#3320 docs: Major enhancements to Query File Defaults docs
  docs/.obsidian/graph.json
  docs/How To/About How Tos.md
  docs/How To/Make a query user interface.md
  docs/Other Plugins/About Other Plugins.md
  docs/Other Plugins/Meta Bind Plugin.md
  docs/Queries/About Queries.md
  docs/Queries/Explaining Queries.md
  docs/Queries/Layout.md
  docs/Queries/Query File Defaults.md
  docs/Scripting/Query Properties.md
  docs/Support and Help/Known Limitations.md
  docs/What is New/Changelog.md
  docs/snippets-embedded-in-multiple-pages/Meta Bind Query Widgets.md
  resources/sample_vaults/Tasks-Demo/Test Data/docs_sample_for_explain_query_file_defaults.md
  src/Query/QueryRendererHelper.ts
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_demo-short-mode_instructions.approved.txt
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_demo-short-mode_yaml.approved.yaml
  tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/Cache.test.ts
  tests/Obsidian/__test_data__/docs_sample_for_explain_query_file_defaults.json
  tests/Query/Explain/DocsSamplesForExplain.test.explain_query_file_defaults_explanation.approved.explanation.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_query_file_defaults_explanation.approved.query.text
  tests/Query/Explain/DocsSamplesForExplain.test.explain_query_file_defaults_file_content.approved.md
  tests/Query/Explain/DocsSamplesForExplain.test.ts
  tests/Query/QueryRendererHelper.test.ts
  tests/TestingTools/ApprovalTestHelpers.ts
Labels: scope: documentation

#3327 chore: Run pre-commit checks on .svelte and json test data files
  lefthook.yml
Labels: type: internal

#3328 refactor: make ListItem class more similar to Task
  src/Task/ListItem.ts
  src/Task/Task.ts
  tests/Task/ListItem.test.ts
Labels: type: internal

#3329 refactor: check or uncheck list items
  src/Task/ListItem.ts
  tests/Task/ListItem.test.ts
Labels: type: internal

#3337 contrib, chore: Improvements to setting up a build environment, mostly for vscode and windows.
  .gitattributes
  .vscode/extensions.json
  .vscode/settings.json
  contributing/Building/Setting up build environment.md
  package.json
Labels: type: internal

#3338 fix: Toggle non-task checkbox lines in tree view
  docs/Queries/Layout.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
  resources/sample_vaults/Tasks-Demo/Test Data/inheritance_non_task_child.md
  src/Obsidian/File.ts
  src/Renderer/QueryResultsRenderer.ts
  src/lib/LogTasksHelper.ts
  src/lib/MockDataCreator.ts
  tests/Obsidian/Cache.test.ts
  tests/Obsidian/__test_data__/inheritance_non_task_child.json
  tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_should_render_non_task_check_box_when_global_filter_is_enabled.approved.html
Labels: scope: rendering of tasks, scope: sub-tasks and super-tasks

#3339 spike: Experimentally cache data from query.allTasks calculations
  resources/sample_vaults/Tasks-Demo/Functions/Custom Filters With Complex Caching.md
  resources/sample_vaults/Tasks-Demo/Functions/Custom Filters With Simple Caching.md
  src/Query/SearchInfo.ts
  src/Scripting/QueryContext.ts
  tests/Query/SearchInfo.test.ts
  tests/Scripting/QueryContext.test.ts
Labels: type: internal, scope: scripting

#3348 fix: Reinstate date picker on iPhone - week starts on Monday
  docs/Editing/Editing Dates.md
  src/ui/Menus/DatePicker.ts
Labels: scope: user interface, display: reading mode

#3349 I18n uk be ru
  i18next-parser.config.js
  src/i18n/i18n.ts
  src/i18n/locales/be.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk.json
Labels: scope: internationalisation

#3350 fix: Only execute searches after Obsidian finishes loading
  src/main.ts
Labels: scope: performance issues
