Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2025-03, with the labels that each got.

#3361 docs: Fix "Unsupported markdown: list" mermaid diagram errors
  docs/Getting Started/Task Dependencies.md
Labels: scope: documentation

#3364 feat: Include layout instructions in 'explain' output
  docs/Queries/Explaining Queries.md
  src/Query/Explain/Explainer.ts
  src/Query/Query.ts
  tests/Query/Explain/DocsSamplesForExplain.test.explain_query_file_defaults_explanation.approved.explanation.text
  tests/Query/Explain/Explainer.test.ts
  tests/Query/QueryRendererHelper.test.ts
Labels: scope: explain

#3365 feat: Explain 'ignore global filter'
  docs/Queries/Global Query.md
  src/Config/GlobalQuery.ts
  src/Query/Explain/Explainer.ts
  src/Query/Query.ts
  src/Query/QueryRendererHelper.ts
  tests/Config/GlobalQuery.test.ts
  tests/Query/Explain/Explainer.test.ts
  tests/Query/QueryRendererHelper.test.ts
Labels: scope: explain

#3370 refactor: `ListItem` construction
  src/Obsidian/FileParser.ts
  src/Task/ListItem.ts
  src/Task/Task.ts
  tests/Task/ListItem.test.ts
  tests/Task/ListItemHelpers.ts
  tests/TestingTools/TaskBuilder.test.ts
Labels: type: internal

#3373 refactor: Provide consistent identicalTo() methods
  src/Scripting/TasksFile.ts
  src/Task/ListItem.ts
  src/Task/Task.ts
  src/Task/TaskLocation.ts
  tests/Scripting/TasksFile.test.ts
  tests/Task/ListItem.test.ts
  tests/Task/TaskLocation.test.ts
Labels: type: internal

#3374 refactor: Finish implementing ListItem.fromListItemLine()
  src/Obsidian/FileParser.ts
  src/Task/ListItem.ts
  src/Task/Task.ts
  tests/Task/ListItem.test.ts
Labels: type: internal

#3357 fix: convert internal heading links when task is rendered in different file
  resources/sample_vaults/Tasks-Demo/Manual Testing/Internal Heading Links/Internal Heading Links.md
  resources/sample_vaults/Tasks-Demo/Manual Testing/Internal Heading Links/Other File.md
  resources/sample_vaults/Tasks-Demo/Test Data/internal_heading_links.md
  src/Renderer/QueryResultsRenderer.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/__test_data__/internal_heading_links.json
  tests/Renderer/QueryResultsRenderer.test.ts
Labels: scope: rendering of tasks

#3377 refactor: Move code for rendering ListItems to TaskLineRenderer
  src/Renderer/QueryResultsRenderer.ts
  src/Renderer/TaskLineRenderer.ts
Labels: type: internal, scope: rendering of tasks

#3380 fix: Prevent use of missing properties in placeholders (#3249)
  src/Scripting/ExpandPlaceholders.ts
  tests/Query/Query.test.ts
  tests/Scripting/ExpandPlaceholders.test.ts
Labels: scope: filters, scope: scripting

#3384 fix: Prevent Auto-Suggest for 'NON_TASK' statuses
  docs/Editing/Auto-Suggest.md
  src/Suggestor/Suggestor.ts
  tests/Suggestor/Suggestor.test.ts
Labels: scope: auto-suggest

#3390 refactor: `ListItem.fromListItemLine()` now correctly returns `null`
  src/Task/ListItem.ts
  tests/Task/ListItem.test.ts
Labels: type: internal

#3391 refactor: Remove need to construct temporary Task objects
  resources/sample_vaults/Tasks-Demo/Test Data/internal_heading_links.md
  src/Obsidian/InlineRenderer.ts
  src/Renderer/QueryResultsRenderer.ts
  src/Renderer/TaskLineRenderer.ts
  tests/Obsidian/__test_data__/internal_heading_links.json
  tests/Renderer/TaskLineRenderer.test.ts
Labels: type: internal, scope: rendering of tasks

#3392 fix: Stable `group by function task.urgency` order
  docs/Queries/Grouping.md
  docs/Scripting/Custom Grouping.md
  src/Query/Filter/FunctionField.ts
  tests/Query/Filter/FunctionField.test.ts
  tests/Query/Group/TaskGroups.test.ts
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.urgency_docs.approved.md
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.urgency_results.approved.txt
  tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
Labels: scope: urgency

#3394 fix: Improve performance when multiple files are edited quickly
  src/Obsidian/Cache.ts
Labels: scope: performance issues, scope: rendering of tasks

#3402 fix: Support Check boxes and List Items in "1)"-style numbered lists
  docs/Getting Started/Getting Started.md
  resources/sample_vaults/Tasks-Demo/Test Data/numbered_list_items_standard.md
  resources/sample_vaults/Tasks-Demo/Test Data/numbered_list_items_with_paren.md
  src/Task/TaskRegularExpressions.ts
  tests/Obsidian/AllCacheSampleData.ts
  tests/Obsidian/Cache.test.ts
  tests/Obsidian/__test_data__/numbered_list_items_standard.json
  tests/Obsidian/__test_data__/numbered_list_items_with_paren.json
  tests/Task/TaskRegularExpressions.test.ts
Labels: scope: parsing markdown
