Repository obsidian-tasks-group/obsidian-tasks, pull requests merged in 2025-08, with the labels that each got.

#3557 refactor: Rename `Link.isLinkTo()` to `Link.linksTo()`
  resources/sample_vaults/Tasks-Demo/How To/Access links.md
  src/Task/Link.ts
  tests/Task/Link.test.ts
Labels: scope: filters

#3569 docs: Initial documentation for Links feature
  docs/Getting Started/About Getting Started.md
  docs/Getting Started/Links.md
  docs/Quick Reference.md
  docs/Scripting/Query Properties.md
  docs/Scripting/Task Properties.md
  docs/Support and Help/Known Limitations.md
  docs/What is New/Changelog.md
  resources/sample_vaults/Tasks-Demo/How To/Access links.md
  resources/sample_vaults/Tasks-Demo/Test Data/query_using_properties.md
  src/Task/Link.ts
  src/Task/LinkResolver.ts
  tests/Obsidian/__test_data__/metadataCache/resolvedLinks.json
  tests/Obsidian/__test_data__/query_using_properties.json
  tests/Scripting/QueryProperties.test.query_file_properties.approved.md
  tests/Scripting/QueryProperties.test.ts
  tests/Scripting/ScriptingTestHelpers.ts
  tests/Scripting/TaskProperties.test.task_links.approved.md
  tests/Scripting/TaskProperties.test.ts
  tests/Task/Link.test.visualise_links_note_bodies.approved.md
  tests/Task/Link.test.visualise_links_outlinks.approved.md
  tests/Task/Link.test.visualise_links_properties.approved.md
Labels: scope: documentation

#3586 refactor: reduce memory usage with dynamic destination path
  src/Scripting/TasksFile.ts
  src/Task/Link.ts
  src/Task/LinkResolver.ts
  src/Task/ListItem.ts
  tests/Scripting/TaskProperties.test.ts
  tests/Task/Link.test.ts
  tests/Task/LinkResolver.test.ts
Labels: type: internal

#3596 feat: redraw search results after global query is edited
  src/Config/SettingsTab.ts
Labels: scope: settings

#3598 docs: Refine 'Priority of Dates' section for recurring tasks
  docs/Getting Started/Recurring Tasks.md
Labels: scope: documentation
